// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionSectionController from "./accordion_section_controller"
application.register("accordion-section", AccordionSectionController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import ArticlesFacetMoreController from "./articles_facet_more_controller"
application.register("articles-facet-more", ArticlesFacetMoreController)

import ArticlesFacetPaginateController from "./articles_facet_paginate_controller"
application.register("articles-facet-paginate", ArticlesFacetPaginateController)

import AsyncCollectionMembersController from "./async_collection_members_controller"
application.register("async-collection-members", AsyncCollectionMembersController)

import AvailabilityController from "./availability_controller"
application.register("availability", AvailabilityController)

import BentoResultCountController from "./bento_result_count_controller"
application.register("bento-result-count", BentoResultCountController)

import BlacklightResultCountController from "./blacklight_result_count_controller"
application.register("blacklight-result-count", BlacklightResultCountController)

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import BrowseNearbyController from "./browse_nearby_controller"
application.register("browse-nearby", BrowseNearbyController)

import ChatHoursController from "./chat_hours_controller"
application.register("chat-hours", ChatHoursController)

import CitationStylePickerController from "./citation_style_picker_controller"
application.register("citation-style-picker", CitationStylePickerController)

import CopyLinkController from "./copy_link_controller"
application.register("copy-link", CopyLinkController)

import CopyTextController from "./copy_text_controller"
application.register("copy-text", CopyTextController)

import CourseReservesController from "./course_reserves_controller"
application.register("course-reserves", CourseReservesController)

import EagerLazyController from "./eager_lazy_controller"
application.register("eager-lazy", EagerLazyController)

import EmailSentController from "./email_sent_controller"
application.register("email-sent", EmailSentController)

import EmbedBrowseController from "./embed_browse_controller"
application.register("embed-browse", EmbedBrowseController)

import ExhibitPanelController from "./exhibit_panel_controller"
application.register("exhibit-panel", ExhibitPanelController)

import FacetCheckboxesController from "./facet_checkboxes_controller"
application.register("facet-checkboxes", FacetCheckboxesController)

import FacetListController from "./facet_list_controller"
application.register("facet-list", FacetListController)

import FacetSearchController from "./facet_search_controller"
application.register("facet-search", FacetSearchController)

import FeedbackFormController from "./feedback_form_controller"
application.register("feedback-form", FeedbackFormController)

import FeedbackModalController from "./feedback_modal_controller"
application.register("feedback-modal", FeedbackModalController)

import FeedbackStandaloneController from "./feedback_standalone_controller"
application.register("feedback-standalone", FeedbackStandaloneController)

import GalleryPreviewController from "./gallery_preview_controller"
application.register("gallery-preview", GalleryPreviewController)

import GoogleCoverImageController from "./google_cover_image_controller"
application.register("google-cover-image", GoogleCoverImageController)

import LibraryH3lpController from "./library_h3lp_controller"
application.register("library-h3lp", LibraryH3lpController)

import LibraryHasController from "./library_has_controller"
application.register("library-has", LibraryHasController)

import LiveLookupController from "./live_lookup_controller"
application.register("live-lookup", LiveLookupController)

import LongTableController from "./long_table_controller"
application.register("long-table", LongTableController)

import LongTextController from "./long_text_controller"
application.register("long-text", LongTextController)

import ManagedPurlController from "./managed_purl_controller"
application.register("managed-purl", ManagedPurlController)

import MetaJsonCheckController from "./meta_json_check_controller"
application.register("meta-json-check", MetaJsonCheckController)

import PreviewEmbedBrowseController from "./preview_embed_browse_controller"
application.register("preview-embed-browse", PreviewEmbedBrowseController)

import PreviewFilmstripController from "./preview_filmstrip_controller"
application.register("preview-filmstrip", PreviewFilmstripController)

import RecaptchaController from "./recaptcha_controller"
application.register("recaptcha", RecaptchaController)

import StackmapController from "./stackmap_controller"
application.register("stackmap", StackmapController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
