// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionSectionController from "./accordion_section_controller"
application.register("accordion-section", AccordionSectionController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import ArticlesFacetMoreController from "./articles_facet_more_controller"
application.register("articles-facet-more", ArticlesFacetMoreController)

import ArticlesFacetPaginateController from "./articles_facet_paginate_controller"
application.register("articles-facet-paginate", ArticlesFacetPaginateController)

import AvailabilityController from "./availability_controller"
application.register("availability", AvailabilityController)

import AvailabilitySearchController from "./availability_search_controller"
application.register("availability-search", AvailabilitySearchController)

import BentoResultCountController from "./bento_result_count_controller"
application.register("bento-result-count", BentoResultCountController)

import BlacklightResultCountController from "./blacklight_result_count_controller"
application.register("blacklight-result-count", BlacklightResultCountController)

import BookmarkController from "./bookmark_controller"
application.register("bookmark", BookmarkController)

import BrowseNearbyController from "./browse_nearby_controller"
application.register("browse-nearby", BrowseNearbyController)

import BrowseRelatedItemsController from "./browse_related_items_controller"
application.register("browse-related-items", BrowseRelatedItemsController)

import ChatHoursController from "./chat_hours_controller"
application.register("chat-hours", ChatHoursController)

import CitationFormatController from "./citation_format_controller"
application.register("citation-format", CitationFormatController)

import CopyLinkController from "./copy_link_controller"
application.register("copy-link", CopyLinkController)

import CopyTextController from "./copy_text_controller"
application.register("copy-text", CopyTextController)

import CourseReservesController from "./course_reserves_controller"
application.register("course-reserves", CourseReservesController)

import DatabaseAutocompleteController from "./database_autocomplete_controller"
application.register("database-autocomplete", DatabaseAutocompleteController)

import EagerLazyController from "./eager_lazy_controller"
application.register("eager-lazy", EagerLazyController)

import EmailSentController from "./email_sent_controller"
application.register("email-sent", EmailSentController)

import EmbedBrowseController from "./embed_browse_controller"
application.register("embed-browse", EmbedBrowseController)

import ExhibitPanelController from "./exhibit_panel_controller"
application.register("exhibit-panel", ExhibitPanelController)

import FacetCheckboxesController from "./facet_checkboxes_controller"
application.register("facet-checkboxes", FacetCheckboxesController)

import FacetListController from "./facet_list_controller"
application.register("facet-list", FacetListController)

import FacetSearchController from "./facet_search_controller"
application.register("facet-search", FacetSearchController)

import FeedbackFormController from "./feedback_form_controller"
application.register("feedback-form", FeedbackFormController)

import FeedbackModalController from "./feedback_modal_controller"
application.register("feedback-modal", FeedbackModalController)

import FeedbackStandaloneController from "./feedback_standalone_controller"
application.register("feedback-standalone", FeedbackStandaloneController)

import GalleryPreviewController from "./gallery_preview_controller"
application.register("gallery-preview", GalleryPreviewController)

import GlobalAlertController from "./global_alert_controller"
application.register("global-alert", GlobalAlertController)

import GoogleCoverImageController from "./google_cover_image_controller"
application.register("google-cover-image", GoogleCoverImageController)

import HomePageSearchController from "./home_page_search_controller"
application.register("home-page-search", HomePageSearchController)

import LibraryH3lpController from "./library_h3lp_controller"
application.register("library-h3lp", LibraryH3lpController)

import LibraryHasController from "./library_has_controller"
application.register("library-has", LibraryHasController)

import ListToggleController from "./list_toggle_controller"
application.register("list-toggle", ListToggleController)

import LocationHoursController from "./location_hours_controller"
application.register("location-hours", LocationHoursController)

import LongTableController from "./long_table_controller"
application.register("long-table", LongTableController)

import LongTextController from "./long_text_controller"
application.register("long-text", LongTextController)

import ManagedPurlController from "./managed_purl_controller"
application.register("managed-purl", ManagedPurlController)

import MetaJsonCheckController from "./meta_json_check_controller"
application.register("meta-json-check", MetaJsonCheckController)

import MiniBentoController from "./mini_bento_controller"
application.register("mini-bento", MiniBentoController)

import MiniMiniBentoController from "./mini_mini_bento_controller"
application.register("mini-mini-bento", MiniMiniBentoController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import PreviewEmbedBrowseController from "./preview_embed_browse_controller"
application.register("preview-embed-browse", PreviewEmbedBrowseController)

import PreviewFilmstripController from "./preview_filmstrip_controller"
application.register("preview-filmstrip", PreviewFilmstripController)

import PurlEmbedController from "./purl_embed_controller"
application.register("purl-embed", PurlEmbedController)

import RecaptchaController from "./recaptcha_controller"
application.register("recaptcha", RecaptchaController)

import ResponsiveAsideController from "./responsive_aside_controller"
application.register("responsive-aside", ResponsiveAsideController)

import SavedListController from "./saved_list_controller"
application.register("saved-list", SavedListController)

import SearchNavbarController from "./search_navbar_controller"
application.register("search-navbar", SearchNavbarController)

import ShowMoreButtonController from "./show_more_button_controller"
application.register("show-more-button", ShowMoreButtonController)

import StackmapController from "./stackmap_controller"
application.register("stackmap", StackmapController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToastMessageListenerController from "./toast_message_listener_controller"
application.register("toast-message-listener", ToastMessageListenerController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
