AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
