inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
