inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0
  NewCops: enable

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/integration/**/*'
    - 'spec/features/**/*'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'app/components/**/*'
