inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0
  NewCops: enable

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/articles_controller.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'lib/holdings/item.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/integration/**/*'
    - 'spec/features/**/*'
    - 'spec/models/**/*'
    - 'spec/requests/**/*'
    - 'spec/routing/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'app/components/**/*'

RSpec/MessageSpies:
  Enabled: false
