require:
- rubocop-rspec
- rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 3.0

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 25

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
