module Constants
  module FolioStatus
    UNPAGEABLE_SPEC_COLL_STATUSES = [
      'In process', 'In process (non-requestable)', 'Missing'
    ]
  end

  RELATOR_TERMS = { 'acp' => 'Art copyist',
                    'act' => 'Actor',
                    'adp' => 'Adapter',
                    'aft' => 'Author of afterword, colophon, etc.',
                    'anl' => 'Analyst',
                    'anm' => 'Animator',
                    'ann' => 'Annotator',
                    'ant' => 'Bibliographic antecedent',
                    'app' => 'Applicant',
                    'aqt' => 'Author in quotations or text abstracts',
                    'arc' => 'Architect',
                    'ard' => 'Artistic director ',
                    'arr' => 'Arranger',
                    'art' => 'Artist',
                    'asg' => 'Assignee',
                    'asn' => 'Associated name',
                    'att' => 'Attributed name',
                    'auc' => 'Auctioneer',
                    'aud' => 'Author of dialog',
                    'aui' => 'Author of introduction',
                    'aus' => 'Author of screenplay',
                    'aut' => 'Author',
                    'bdd' => 'Binding designer',
                    'bjd' => 'Bookjacket designer',
                    'bkd' => 'Book designer',
                    'bkp' => 'Book producer',
                    'bnd' => 'Binder',
                    'bpd' => 'Bookplate designer',
                    'bsl' => 'Bookseller',
                    'ccp' => 'Conceptor',
                    'chr' => 'Choreographer',
                    'clb' => 'Collaborator',
                    'cli' => 'Client',
                    'cll' => 'Calligrapher',
                    'clt' => 'Collotyper',
                    'cmm' => 'Commentator',
                    'cmp' => 'Composer',
                    'cmt' => 'Compositor',
                    'cng' => 'Cinematographer',
                    'cnd' => 'Conductor',
                    'cns' => 'Censor',
                    'coe' => 'Contestant -appellee',
                    'col' => 'Collector',
                    'com' => 'Compiler',
                    'cos' => 'Contestant',
                    'cot' => 'Contestant -appellant',
                    'cov' => 'Cover designer',
                    'cpc' => 'Copyright claimant',
                    'cpe' => 'Complainant-appellee',
                    'cph' => 'Copyright holder',
                    'cpl' => 'Complainant',
                    'cpt' => 'Complainant-appellant',
                    'cre' => 'Creator',
                    'crp' => 'Correspondent',
                    'crr' => 'Corrector',
                    'csl' => 'Consultant',
                    'csp' => 'Consultant to a project',
                    'cst' => 'Costume designer',
                    'ctb' => 'Contributor',
                    'cte' => 'Contestee-appellee',
                    'ctg' => 'Cartographer',
                    'ctr' => 'Contractor',
                    'cts' => 'Contestee',
                    'ctt' => 'Contestee-appellant',
                    'cur' => 'Curator',
                    'cwt' => 'Commentator for written text',
                    'dfd' => 'Defendant',
                    'dfe' => 'Defendant-appellee',
                    'dft' => 'Defendant-appellant',
                    'dgg' => 'Degree grantor',
                    'dis' => 'Dissertant',
                    'dln' => 'Delineator',
                    'dnc' => 'Dancer',
                    'dnr' => 'Donor',
                    'dpc' => 'Depicted',
                    'dpt' => 'Depositor',
                    'drm' => 'Draftsman',
                    'drt' => 'Director',
                    'dsr' => 'Designer',
                    'dst' => 'Distributor',
                    'dtc' => 'Data contributor ',
                    'dte' => 'Dedicatee',
                    'dtm' => 'Data manager ',
                    'dto' => 'Dedicator',
                    'dub' => 'Dubious author',
                    'edt' => 'Editor',
                    'egr' => 'Engraver',
                    'elg' => 'Electrician ',
                    'elt' => 'Electrotyper',
                    'eng' => 'Engineer',
                    'etr' => 'Etcher',
                    'exp' => 'Expert',
                    'fac' => 'Facsimilist',
                    'fld' => 'Field director ',
                    'flm' => 'Film editor',
                    'fmo' => 'Former owner',
                    'fpy' => 'First party',
                    'fnd' => 'Funder',
                    'frg' => 'Forger',
                    'gis' => 'Geographic information specialist ',
                    'grt' => 'Graphic technician',
                    'hnr' => 'Honoree',
                    'hst' => 'Host',
                    'ill' => 'Illustrator',
                    'ilu' => 'Illuminator',
                    'ins' => 'Inscriber',
                    'inv' => 'Inventor',
                    'itr' => 'Instrumentalist',
                    'ive' => 'Interviewee',
                    'ivr' => 'Interviewer',
                    'lbr' => 'Laboratory ',
                    'lbt' => 'Librettist',
                    'ldr' => 'Laboratory director ',
                    'led' => 'Lead',
                    'lee' => 'Libelee-appellee',
                    'lel' => 'Libelee',
                    'len' => 'Lender',
                    'let' => 'Libelee-appellant',
                    'lgd' => 'Lighting designer',
                    'lie' => 'Libelant-appellee',
                    'lil' => 'Libelant',
                    'lit' => 'Libelant-appellant',
                    'lsa' => 'Landscape architect',
                    'lse' => 'Licensee',
                    'lso' => 'Licensor',
                    'ltg' => 'Lithographer',
                    'lyr' => 'Lyricist',
                    'mcp' => 'Music copyist',
                    'mfr' => 'Manufacturer',
                    'mdc' => 'Metadata contact',
                    'mod' => 'Moderator',
                    'mon' => 'Monitor',
                    'mrk' => 'Markup editor',
                    'msd' => 'Musical director',
                    'mte' => 'Metal-engraver',
                    'mus' => 'Musician',
                    'nrt' => 'Narrator',
                    'opn' => 'Opponent',
                    'org' => 'Originator',
                    'orm' => 'Organizer of meeting',
                    'oth' => 'Other',
                    'own' => 'Owner',
                    'pat' => 'Patron',
                    'pbd' => 'Publishing director',
                    'pbl' => 'Publisher',
                    'pdr' => 'Project director',
                    'pfr' => 'Proofreader',
                    'pht' => 'Photographer',
                    'plt' => 'Platemaker',
                    'pma' => 'Permitting agency',
                    'pmn' => 'Production manager',
                    'pop' => 'Printer of plates',
                    'ppm' => 'Papermaker',
                    'ppt' => 'Puppeteer',
                    'prc' => 'Process contact',
                    'prd' => 'Production personnel',
                    'prf' => 'Performer',
                    'prg' => 'Programmer',
                    'prm' => 'Printmaker',
                    'pro' => 'Producer',
                    'prt' => 'Printer',
                    'pta' => 'Patent applicant',
                    'pte' => 'Plaintiff -appellee',
                    'ptf' => 'Plaintiff',
                    'pth' => 'Patent holder',
                    'ptt' => 'Plaintiff-appellant',
                    'rbr' => 'Rubricator',
                    'rce' => 'Recording engineer',
                    'rcp' => 'Recipient',
                    'red' => 'Redactor',
                    'ren' => 'Renderer',
                    'res' => 'Researcher',
                    'rev' => 'Reviewer',
                    'rps' => 'Repository',
                    'rpt' => 'Reporter',
                    'rpy' => 'Responsible party',
                    'rse' => 'Respondent-appellee',
                    'rsg' => 'Restager',
                    'rsp' => 'Respondent',
                    'rst' => 'Respondent-appellant',
                    'rth' => 'Research team head',
                    'rtm' => 'Research team member',
                    'sad' => 'Scientific advisor',
                    'sce' => 'Scenarist',
                    'scl' => 'Sculptor',
                    'scr' => 'Scribe',
                    'sds' => 'Sound designer',
                    'sec' => 'Secretary',
                    'sgn' => 'Signer',
                    'sht' => 'Supporting host',
                    'sng' => 'Singer',
                    'spk' => 'Speaker',
                    'spn' => 'Sponsor',
                    'spy' => 'Second party',
                    'srv' => 'Surveyor',
                    'std' => 'Set designer',
                    'stl' => 'Storyteller',
                    'stm' => 'Stage manager',
                    'stn' => 'Standards body',
                    'str' => 'Stereotyper',
                    'tcd' => 'Technical director',
                    'tch' => 'Teacher',
                    'ths' => 'Thesis advisor',
                    'trc' => 'Transcriber',
                    'trl' => 'Translator',
                    'tyd' => 'Type designer',
                    'tyg' => 'Typographer',
                    'vdg' => 'Videographer',
                    'voc' => 'Vocalist',
                    'wam' => 'Writer of accompanying material',
                    'wdc' => 'Woodcutter',
                    'wde' => 'Wood -engraver',
                    'wit' => 'Witness' }
  LOCS = {
    '13TH-FLOOR' => '13th floor',
    '15TH-FLOOR' => '15th floor',
    '1ST-FLOOR' => 'Ask at circulation desk',
    '2ND-FLOOR' => 'Ask at circulation desk',
    '2NDFLR-REF' => 'Ask at circulation desk',
    '3RD-FLOOR' => 'Ask at circulation desk',
    '3RDFLR-REF' => 'Ask at circulation desk',
    'ACAD-DATA' => 'Social Science Data and Software',
    'ARABIC' => 'Arabic',
    'ARS-LOAN' => 'In Archive of Recorded Sound: Ask at service desk',
    'ART-AT-ENG' => 'Currently at Terman Library',
    'ART-LOAN' => 'On hold for a borrower',
    'ART-RESV' => 'On reserve: Ask at circulation desk',
    'ARTLCKL' => 'Locked stacks (Large)',
    'ARTLCKL-R' => 'Locked stacks (Large)',
    'ARTLCKM' => 'Locked stacks (Medium)',
    'ARTLCKM-R' => 'Locked stacks (Medium)',
    'ARTLCKO' => 'Locked stacks (Oversize)',
    'ARTLCKO-R' => 'Locked stacks (Oversize)',
    'ARTLCKS' => 'Locked stacks (Small)',
    'ARTLCKS-R' => 'Locked stacks (Small)',
    'ARTVAULT' => 'Art Vault',
    'ASK@EASIA' => 'Ask at circulation desk',
    'ASK@GSB' => 'Check Business Library catalog for status',
    'ASK@LANE' => 'Check Lane Library catalog for status',
    'ASSMD-LOST' => 'Checked out - Overdue',
    'AT-REPAIR' => 'Out for repair',
    'ATCIRCDESK' => 'Ask at circulation desk',
    'ATLASES' => 'Atlas Section',
    'AVAIL_SOON' => 'Ask at circulation desk',
    'B&F-HOLD' => 'At bindery',
    'BARCHAS' => 'Barchas Collection',
    'BASEMENT' => 'Basement',
    'BASEMNT' => 'Basement',
    'BENDER' => 'Bender Room',
    'BIB-INDEX' => 'Bibliographies & Indexes section',
    'BILLED-OD' => 'Overdue',
    'BINDERY' => 'At bindery',
    'BIO-LOAN' => 'On hold for a borrower',
    'BIO-RESV' => 'On reserve: Ask at circulation desk',
    'BIO-TEMP' => 'Ask at circulation desk',
    'BOOKCAB' => 'Teaming room: book cabinet',
    'BOX-COLL' => 'Box Collection',
    'BRAN-RESV' => 'On reserve at Branner Library',
    'BRIT-DOCS' => 'British Government Documents',
    'BUS-ARCH' => 'Archives: Ask at i-Desk',
    'BUS-CMC' => 'Career Corner',
    'BUS-COMPF' => 'Computer files: Ask at i-Desk',
    'BUS-LOAN' => 'On hold for a borrower',
    'BUS-LOCKED' => 'Locked stacks: Ask at i-Desk',
    'BUS-MAKENA' => 'Makena Capital Traders Pit',
    'BUS-PER' => 'Periodicals',
    'BUS-POP' => 'Popular Business Books',
    'BUS-RESV' => 'On reserve at Business Library',
    'BUS-STACKS' => 'Stacks',
    'BUS-TEMP' => 'Ask at i-Desk',
    'BUSDISPLAY' => 'Display shelves',
    'CALIF-DOCS' => 'California State Documents',
    'CASE-MP' => 'Map Center (case map)',
    'CCRMA' => 'Ask at circulation desk',
    'CDL' => 'Reserved for digital lending',
    'CDL-2NDFL' => 'Ask at circulation desk',
    'CDP' => 'Ask at circulation desk',
    'CDP-CHI' => 'Ask at circulation desk',
    'CDP-GER' => 'Ask at circulation desk',
    'CDP-JUDA' => 'Ask at circulation desk',
    'CDP-LAT' => 'Ask at circulation desk',
    'CDP-ROM' => 'Ask at circulation desk',
    'CDP-SLAV' => 'Ask at circulation desk',
    'CHE-LOAN' => 'On hold for a borrower',
    # 'CHECKEDOUT' => 'Checked out - Due <date>',
    'CHECKSHELF' => 'Check shelf',
    'CHEM-RESV' => 'On reserve: Ask at circulation desk',
    'CHINESE' => 'Chinese Collection',
    'CHKD-OUT-D' => 'Ask at circulation desk',
    'COLL-WORKS' => 'Storage area: Collected Works section',
    'COMPACT' => 'Ask at circulation desk',
    'COOKBOOK' => 'Cookbooks',
    'COURSE-RES' => 'Ask at circulation desk',
    'COURSE-VID' => 'Ask at circulation desk',
    'CPM-HOLDS' => 'At bindery',
    'CROTHERS' => 'Crothers Collection',
    'CURRENTPER' => 'Current periodicals',
    'CURRICULUM' => 'Curriculum at Green',
    'CURRSTOR' => 'Ask at circulation desk',
    'DSPLAY-1ST' => '1st floor display case',
    'DSPLAY-2ND' => '2nd floor display case',
    'DOMESTIC' => 'Domestic',
    'EAL-SETS' => 'East Asia Big Sets',
    'EAL-STKS-C' => 'Chinese Collection',
    'EAL-STKS-J' => 'Japanese Collection',
    'EAL-STKS-K' => 'Korean Collection',
    'EALSAL-CHN' => 'Ask at circulation desk',
    'EALSAL-JPN' => 'Ask at circulation desk',
    'EALSAL-KOR' => 'Ask at circulation desk',
    'EAR-LOAN' => 'On hold for a borrower',
    'EARTH-RESV' => 'On reserve: Ask at circulation desk',
    'EAS-LOAN' => 'On hold for a borrower',
    'EAS-RESV' => 'On reserve: Ask at circulation desk',
    'EDI' => 'In process',
    'EDU-LOAN' => 'On hold for a borrower',
    'EDU-RESV' => 'On reserve: Ask at circulation desk',
    'ENDPROCESS' => 'In process',
    'ENG-LOAN' => 'On hold for a borrower',
    'ENG-RESV' => 'On reserve: Ask at circulation desk',
    'ENGDISPLAY' => 'Magazine display (latest issues only)',
    'EQUIPMENT' => 'Equipment: Ask at circulation desk',
    'EXPEDITION' => 'Expedition: Locked Stacks',
    'EYLESAISLE' => 'Eyles aisle',
    'FACULTY' => 'Faculty',
    'FED-DOCS' => 'US Federal Documents',
    'FELT-STOR' => 'Felton Collection',
    'FELTON' => 'Felton Collection',
    'FELTON-30' => 'Felton Collection',
    'FOLIO' => 'Folios',
    'FOLIO-3RD' => 'Folios on the 3rd floor',
    'FOLIO-BAS' => 'Folios in the basement',
    'FOLIO-CHN' => 'Chinese Folios',
    'FOLIO-FLAT' => 'Flat folios',
    'FOLIO-JPN' => 'Japanese Folios',
    'FOLIO-KOR' => 'Korean Folios',
    'FOREIGN' => 'Foreign Government Documents',
    'FORN-DOCS' => 'Foreign Government Documents',
    'FRECOT' => 'Frecot Collection',
    'GADGETBAR' => 'Gadget Bar',
    'GOLDSTAR' => 'Ask at circulation desk',
    'GRE-LOAN' => 'On hold for a borrower',
    'GREEN-RESV' => 'On reserve: Ask at circulation desk',
    'GSB-RESV' => 'On reserve at Business Library',
    'GUNST' => 'Gunst Collection',
    'GUNST-30' => 'Gunst Collection',
    'GUNST-STOR' => 'Gunst Collection',
    'HAS-ATLAS' => 'Lane Reading Room: Atlases',
    'HAS-CA' => 'Lane Reading Room: California history',
    'HAS-DIGIT' => 'Lane Reading Room: Digital culture and humanities computing',
    'HAS-FIC' => 'Lane Reading Room: Recent fiction',
    'HAS-FOLIO' => 'Lane Reading Room: Oversize books',
    'HAS-JOURN' => 'Lane Reading Room: Journals',
    'HAS-LIT' => 'Lane Reading Room',
    'HAS-NEWBK' => 'Lane Reading Room: New books',
    'HAS-RR' => 'Lane Reading Room: Ready reference',
    'HAS-SU' => 'Lane Reading Room: Stanford history',
    'HASRC' => 'Lane Reading Room: Reference',
    'HH-FOYER' => 'Hohbach Hall: Foyer bookshelf',
    'HMS-PAGE' => 'In transit to main campus',
    'HMS-RETURN' => 'In transit to Hopkins',
    'HOLDS' => 'Ask at circulation desk',
    'HOO-LOAN' => 'On hold for a borrower',
    'HOOV-RESV' => 'On reserve: Ask at circulation desk',
    'HOP-LOAN' => 'On hold for a borrower',
    'HOP-RESV' => 'On reserve: Ask at circulation desk',
    'HV-TRANS' => 'In transit',
    'HVA-LOAN' => 'On hold for a borrower',
    'HY-PAGE-EA' => 'Harvard-Yenching Collection: Must be picked up at East Asia Library',
    'IC' => 'Information Center',
    'IC-ATLAS' => 'Information Center: Atlases',
    'IC-CDROM' => 'Information Center: CDROMs',
    'IC-DESK' => 'Information Center desk',
    'IC-DISPLAY' => 'Information Center display',
    'IC-EXHIBIT' => 'Information Center exhibit',
    'IC-NEWS' => 'Information Center: Newspapers',
    'IC-RREF' => 'Hohbach Hall: Reference',
    'IC-STATS' => 'Information Center: Statistics',
    'ILB-LOAN' => 'On hold for a borrower',
    'ILL' => 'Ask at circulation desk',
    'ILL-OFFICE' => 'Ask at circulation desk',
    'INDEXES' => 'Indexes',
    'INPROCESS' => 'In process',
    'INSHIPPING' => 'In process',
    'INSTRUCTOR' => "Instructor's copy",
    'INTCOLLCAT' => 'International college catalogs',
    'INTERNET' => 'Online resource',
    'INTL-DOCS' => 'International Government Documents',
    'INTRANSIT' => 'In transit',
    'JAPANESE' => 'Japanese Collection',
    'KOREAN' => 'Korean Collection',
    'L-PAGE-EA' => 'Request for use in East Asia Library',
    'LAC' => 'In process',
    'LANE-RESV' => 'On reserve at Lane Library',
    'LANG-LAB' => 'Language Lab',
    'LANG-RESV' => 'Language Lab reserves',
    'LAW-ARCHIV' => 'Archives: Ask at circulation desk',
    'LAW-BIND' => 'At bindery',
    'LAW-CAREER' => 'Law Careers collection: Ask at circulation desk',
    'LAW-CIRC' => 'At Law Library circulation desk',
    'LAW-DSPLAY' => 'Law temporary display: ask at circulation desk',
    'LAW-LOAN' => 'On hold for a borrower',
    'LAW-RESV' => 'On reserve: Teaming room',
    'LAW-REVIEW' => 'Law Review',
    'LAW-SPEC' => 'Law Collection',
    'LCK-STOR' => 'Locked storage: Ask at circulation desk',
    'LCKBYTITL' => 'Locked Stacks: ask at circulation desk',
    'LEWIS-COLL' => 'Lewis Collection',
    'LL-NEWS' => 'Lower level: Newspapers',
    'LOAN-DESK' => 'Ask at circulation desk',
    'LOCK-CHN' => 'Locked stacks: Ask at circulation desk',
    'LOCK-HOLDS' => 'Locked stacks: Ask at circulation desk',
    'LOCK-JPN' => 'Locked stacks: Ask at circulation desk',
    'LOCK-KOR' => 'Locked stacks: Ask at circulation desk',
    'LOCK-STK-O' => 'Locked stacks (Oversize): Ask at circulation desk',
    'LOCKED-DIS' => 'Locked stacks: Ask at circulation desk',
    'LOCKED-MAP' => 'Locked map files: Ask at circulation desk',
    'LOCKED-STK' => 'Locked stacks: Ask at circulation desk',
    'LOST-ASSUM' => 'Checked out - Overdue',
    'LOST-CLAIM' => 'Lost',
    'LOST-PAID' => 'Lost',
    'MAGAZINE' => 'Hohbach Hall: Magazine Collection',
    'MANNING' => 'Manning Collection',
    'MANUSCRIPT' => 'Manuscript Collection',
    'MAP-CASES' => 'Map cases',
    'MAP-FILE' => 'Map files',
    'MAP-REF' => 'Reference maps',
    'MAP-STOR' => 'Map storage: Ask at circulation desk',
    'MAPS' => 'Maps',
    'MAT-LOAN' => 'On hold for a borrower',
    'MATH-ARCH' => 'Ask at circulation desk',
    'MATH-RESV' => 'On reserve: Ask at circulation desk',
    'MATH-TECH' => 'Ask at circulation desk',
    'MATH-TEMP' => 'Ask at circulation desk',
    'MEDIA' => 'Media',
    'MEDIA-30' => 'Media',
    'MEDIA-MTXT' => 'Media & Microtext Center',
    'MEDIA-RESV' => 'On reserve: Ask at circulation desk',
    'MEDIAX' => 'Media Collection',
    'MEDIAX-30' => 'Media Collection',
    'MEDIEVALRM' => 'Medieval Studies (Raubitschek) Room',
    'MEMLIBMUS' => 'Memorial Library of Music',
    'MEY-LOAN' => 'On hold for a borrower',
    'MEYER-RESV' => 'Ask at circulation desk',
    'MEZZANINE' => 'Mezzanine',
    'MEZZ-STOR' => 'Ask at circulation desk',
    'MICROFICHE' => 'Microfiche',
    'MICROFILM' => 'Microfilm',
    'MICROTEXT' => 'Microtext',
    'MINIATURE' => 'Miniature',
    'MISS-INPRO' => 'Missing',
    'MISSING' => 'Missing',
    'MM-ARTCAB' => 'Microfiche collection B',
    'MM-BUSCAB' => 'Microfiche collection A',
    'MM-DIZOCAB' => 'Microfiche collection D',
    'MM-MATHCAB' => 'Microfiche collection C',
    'MM-CDCAB' => 'Ask at Media Microtext desk',
    'MM-CMPACT2' => 'Ask at Media Microtext desk',
    'MM-OVERSIZ' => 'Ask at Media Microtext desk',
    'MM-STACKS' => 'Ask at Media Microtext desk',
    'MP-CASE-LG' => 'Map Center (large case)',
    'MP-CASE-MD' => 'Map Center (medium case)',
    'MP-CASE-RF' => 'Raised Relief Maps',
    'MP-CASE-SM' => 'Map Center (small case)',
    'MSS-10' => 'Manuscript Collection',
    'MSS-20' => 'Manuscript Collection',
    'MSS-30' => 'Manuscript Collection',
    'MSSX' => 'Manuscript Collection',
    'MSSX-30' => 'Manuscript Collection',
    'MUS-LOAN' => 'On hold for a borrower',
    'MUS-NOCIRC' => 'Ask at circulation desk',
    'MUS-TXTBK' => 'Ask at circulation desk',
    'MUSIC-RESV' => 'On reserve: Ask at circulation desk',
    'ND-PAGE-EA' => 'NDC Collection: Must be picked up in East Asia Library',
    'NEWBOOKS' => 'New books shelf',
    'NEWS-STKS' => 'Newspaper stacks',
    'NEWSPAPERS' => 'Newspapers',
    'NEWTON' => 'Newton Collection',
    'ON-ORDER' => 'On order',
    'OPEN-RES' => 'Open reserves',
    'OUT-TRAVEL' => 'Outdoors & travel',
    'OVERSIZED' => 'Oversized',
    'PAGE-AR' => 'For use in Art & Architecture Library or Special Collections',
    'PAGE-AS' => 'For use in Archive of Recorded Sound',
    'PAGE-BU' => 'Request for pickup at Business Library',
    'PAGE-EA' => 'For use in East Asia Library',
    'PAGE-ED' => 'For use in Cubberley Library',
    'PAGE-EN' => 'For use in Terman Library',
    'PAGE-ES' => 'For use in Branner Library',
    'PAGE-FC' => 'For use in Art & Architecture Library, Music Library or Special Collections',
    'PAGE-GR' => 'For use in Green Library',
    'PAGE-HA' => 'For use in Hoover Archives',
    'PAGE-HP' => 'For use in Miller Library or Green Library',
    'PAGE-HV' => 'For use in Hoover Library',
    'PAGE-IRON' => 'Offsite',
    'PAGE-IRON2' => 'Offsite',
    'PAGE-LN' => 'Paged to Medical Library',
    'PAGE-LP' => 'Request for pickup at Music Library or Media & Microtext Center',
    'PAGE-LW' => 'For use in Law Library',
    'PAGE-MA' => 'For use in Miller Library or Green Library',
    'PAGE-MD' => 'For use in Green Media & Microtext Center',
    'PAGE-MM' => 'Request for pickup at Media & Microtext Center',
    'PAGE-MP' => 'Request for pickup at Branner Library',
    'PAGE-MU' => 'For use in Music Library',
    'PAGE-RM' => 'For use in David Rumsey Map Center',
    'PAGE-SI' => 'For use in Science Library',
    'PAGE-SP' => 'For use in Special Collections Reading Room',
    'PAGE-TA' => 'For use in Philosophy Library',
    'PERM-RES' => 'Permanent reserve: Ask at circulation desk',
    'PERSIAN' => 'Persian',
    'PGDFROMSAL' => 'In transit to campus library',
    'PHOTO-PERM' => 'Ask at circulation desk',
    'PHY-LOAN' => 'On hold for a borrower',
    'PHYS-RESV' => 'Ask at circulation desk',
    'PHYSTEMP' => 'Currently online only',
    'POPSCI' => 'Popular science',
    'PUB-TECH' => 'Ask at circulation desk',
    'R-FOLIO' => 'Folio (Limited loan)',
    'R-FOLIO-FL' => 'Flat folio (Limited loan)',
    'R-MINIATUR' => 'Miniature (Limited loan)',
    'R-STACKS' => 'Stacks (Limited loan)',
    'RARE-BOOKS' => 'Rare Books Collection',
    'RARE-STOR' => 'Rare Books Collection',
    'RAUB-COLL' => 'Raubitschek Collection of Papyrology and Epigraphy',
    'RAUB-NUM' => 'Frank L. Kovacs Numismatic Library',
    'RBC-30' => 'Rare Books Collection',
    'RBCX' => 'Rare Books Collection',
    'RBCX-30' => 'Rare Books Collection',
    'READING-RM' => 'Reading Room',
    'READY-REF' => 'Reference',
    'RECORDINGS' => 'Recordings',
    'REF-CHN' => 'Reference',
    'REF-DESK' => 'Reference desk',
    'REF-FOLIO' => 'Reference: Oversize',
    'REF-JPN' => 'Reference',
    'REF-KOR' => 'Reference',
    'REF-SERIAL' => 'Reference',
    'REFERENCE' => 'Reference',
    'REPAIR' => 'Out for repair',
    'RESEARCH' => 'Research',
    'RESERVES' => 'Reserves',
    'RESV-DESKS' => 'Ask at circulation desk',
    'RET-REF' => 'Retired Reference',
    'ROB-STOR' => 'Robinson Collection',
    'ROBINSON' => 'Robinson Collection',
    'RUM-LOAN' => 'In Map Center: Ask at service desk',
    'RUMSEY' => 'Rumsey Collection',
    'RUMSEYREF' => 'David Rumsey Map Center',
    'RUMXEMPLAR' => 'Map Center (Exemplars)',
    'RWC-LOAN' => 'On hold for a borrower',
    'SAFETY' => 'Safety Collection',
    'SAL-ARABIC' => 'Temporary shelving for Arabic materials',
    'SAL-FOLIO' => 'Temporary shelving for Folio materials',
    'SAL-LOAN' => 'On hold for a borrower',
    'SAL-MUSIC' => 'Temporary shelving for Music materials',
    'SAL-PAGE' => 'Temporary shelving',
    'SAL-RETURN' => 'In transit to SAL1&2',
    'SAL-SERG' => 'Science and Engineering shelving at SAL',
    'SAL-TEMP' => 'Temporary shelving',
    'SALTURKISH' => 'Temporary shelving for Turkish materials',
    'SAMSON' => 'Samson Collection',
    'SCBS' => 'Stanford Center for Buddhist Studies (Bldg. 70)',
    'SCORES' => 'Scores',
    'SCI-LOAN' => 'On hold for a borrower',
    'SCI-RESV' => 'On reserve: Ask at circulation desk',
    'SCIFI' => 'Science Fiction Collection',
    'SEE-ARCHIV' => 'Currently at Hoover Archives',
    'SEE-EASTA' => 'Ask at circulation desk',
    'SEE-LOAN' => 'Ask at circulation desk',
    'SEE-OTHER' => 'See linked record to request items bound together',
    'SERIALS' => 'Serials',
    'SETS' => 'Big Sets',
    'SGC' => 'Stanford Geospatial Center',
    'SHELBYSER' => 'Serials',
    'SHELBYTITL' => 'Serials',
    'SL3-LOAN' => 'Ask at circulation desk',
    'SLN-LOAN' => 'Ask at circulation desk',
    'SOUTH-MEZZ' => 'Stacks',
    'SPE-LOAN' => 'In Reading Room: Ask at service desk',
    'SPEC-INPRO' => 'In process',
    'SPEC-STOR' => 'In storage, not available',
    'SPECDESK' => 'In Reading Room: Ask at service desk',
    'SSRC' => 'Jonsson Social Sciences Reading Room',
    'SSRC-ANRPT' => 'Ask at circulation desk',
    'SSRC-ATLAS' => 'Jonsson Social Sciences Reading Room: Atlas stand',
    'SSRC-CLASS' => 'Jonsson Social Sciences Reading Room: Classic texts',
    'SSRC-CSLI' => 'Jonsson Social Sciences Reading Room: CSLI publications',
    'SSRC-CURR' => 'Jonsson Social Sciences Reading Room',
    'SSRC-DATA' => 'Velma Denning Room (Social Science Data and Software)',
    'SSRC-DESK' => 'Jonsson Social Sciences Reading Room',
    'SSRC-DOCS' => 'Jonsson Social Sciences Reading Room: Atrium',
    'SSRC-EDU' => 'Jonsson Social Sciences Reading Room: Education Reference',
    'SSRC-FICHE' => 'Bing Wing lower level: Microform cabinets',
    'SSRC-FILM' => 'Bing Wing lower level: Microform cabinets',
    'SSRC-NEWBK' => 'Jonsson Social Sciences Reading Room: New books',
    'SSRC-NWDOC' => 'Ask at circulation desk',
    'SSRC-SLS' => 'Ask at circulation desk',
    'SSRC-STATS' => 'Jonsson Social Sciences Reading Room: Statistics',
    'SSRC-SSDS' => 'Velma Denning Room (Social Science Data and Software)',
    'STACKS' => 'Stacks',
    'STACKS-1' => 'Stacks 1',
    'STACKS-2' => 'Stacks 2',
    'STACKS-3' => 'Stacks 3',
    'STACKS-30' => 'Offsite',
    'STACKS-BW' => 'Bound with another item',
    'STAFF' => 'Ask at circulation desk',
    'STK-GEMS' => 'Collection Gems',
    'STK-NOCIRC' => 'Stacks',
    'STK-SM' => 'Map Center (small stacks)',
    'STK-MED' => 'Map Center (medium stacks)',
    'STK-LG' => 'Map Center (large stacks)',
    'STK-XLG' => 'Map Center (x-large stacks)',
    'STKS1-NEW' => 'New books shelf',
    'STORAGE' => 'Ask at circulation desk',
    'STORBYTITL' => 'Storage area: Shelved by title',
    'STUDY-AIDS' => 'Study aids',
    'SUL-BIND' => 'At bindery',
    'SUL-LOAN' => 'Ask at circulation desk',
    'SULBIND-WA' => 'At bindery',
    'E-RESV' => 'Online item on course reading list',
    'SW-RESERVE-DESK' => 'On reserve: Ask at circulation desk',
    'TAN-LOAN' => 'On hold for a borrower',
    'TANN-RESV' => 'On reserve: Ask at circulation desk',
    'TAUBE' => 'Taube Collection',
    'TECH-ACQ' => 'In Tech Services',
    'TECH-CAT' => 'In Tech Services',
    'TECH-CONS' => 'In Tech Services',
    'TECH-DESK' => 'The Tech Desk',
    'TECH-PROC' => 'In Tech Services',
    'TECH-RPTS' => 'Technical Reports',
    'TECH-SER' => 'In Tech Services',
    'TECH-SERV' => 'In Tech Services',
    'TEMP-LL' => 'Ask at circulation desk',
    'TEMP-LOC' => 'Ask at circulation desk',
    'TERM-COLL' => 'Terman Collection: Ask at circulation desk',
    'THEA-STOR' => 'Theatre Collection',
    'THEATRE' => 'Theatre Collection',
    'THESES' => 'Theses',
    'TIMO-COLL' => 'Timoshenko Collection: Ask at circulation desk',
    'TINY' => 'Miniature',
    'TRES-LAIR' => 'Ask at circulation desk',
    'TURKISH' => 'Turkish',
    'U-ARCHIVES' => 'University Archives',
    'UARCH-30' => 'University Archives',
    'UARCH-REF' => 'University Archives reference',
    'UARCH-STOR' => 'University Archives',
    'UARCHX' => 'University Archives',
    'UARCHX-30' => 'University Archives',
    'UNCAT' => 'Ask at circulation desk',
    'UNDERGRAD' => 'Undergraduate Collection',
    'UNKNOWN' => 'Ask at circulation desk',
    'US-LOCAL' => 'US Local Documents',
    'US-STATE' => 'US State Documents',
    'VARIES' => 'Ask at circulation desk',
    'VAULT' => 'Vault',
    'VROOMAN' => 'Vrooman Collection',
    'VROOMAN2' => 'Vrooman Collection, 2nd Floor',
    'VROOMAN-OV' => 'Vrooman Collection, Oversize',
    'W7-ATLASES' => 'Map Center',
    'W7-BXLG-HM' => 'Map Center (W7 historic large box)',
    'W7-BXO' => 'Map Center (W7 box other)',
    'W7-BXSM-HM' => 'Map Center (W7 historic small box)',
    'W7-CASE-HM' => 'Map Center (W7 historic map case)',
    'W7-CASE-MP' => 'Map Center (W7 case map)',
    'W7-CASE-MT' => 'Map Center (W7 matted maps)',
    'W7-CASE-MD' => 'Map Center (W7 map case)',
    'W7-CATALOG' => 'Map Center (W7 catalog)',
    'W7-CONSERV' => 'Map Center (W7 conservation)',
    'W7-M-CASES' => 'Map Center',
    'W7-MAP-BXS' => 'Map Center (W7 small box)',
    'W7-MAP-BXL' => 'Map Center (W7 large box)',
    'W7-MAP-XLG' => 'Map Center (W7 x-large maps)',
    'W7-POCK-LG' => 'Map Center (W7 large pocket maps)',
    'W7-POCK-RG' => 'Map Center (W7 regular pocket maps)',
    'W7-ROLLED' => 'Map Center (W7 rolled)',
    'W7-SANBORN' => 'Map Center (W7 Sanborn case)',
    'W7-STK-SM' => 'Map Center (W7 small stacks)',
    'W7-STK-MED' => 'Map Center (W7 medium stacks)',
    'W7-STK-LG' => 'Map Center (W7 large stacks)',
    'W7-STK-XLG' => 'Map Center (W7 x-large stacks)',
    'W7-STKS' => 'Map Center',
    'W7-STORAGE' => 'Map Center (W7 storage)',
    'W7-OBJECTS' => 'Map Center (W7 objects)',
    'W7-FOLIO' => 'Map Center (W7 folios)',
    'W7-REF' => 'Map Center (W7 reference)',
    'W7-STAFF' => 'Map Center (W7 staff)',
    'W7-STFSHD' => 'Map Center (W7 shadowed)',
    'W7-FRAME' => 'Map Center (W7 framed)',
    'W7-POCKET' => 'Map Center (W7 pocket)',
    'WELLNESS' => ' Wellness wall',
    'WEST-7B' => 'Ask at circulation desk'
  }.freeze

  UNAVAILABLE_LOCS = ['ASSMD-LOST',
                      'AT-REPAIR',
                      'AVAIL_SOON',
                      'B&F-HOLD',
                      'BILLED-OD',
                      'BINDERY',
                      # "CHECKEDOUT",
                      'CDL',
                      'CHKD-OUT-D',
                      'CPM-HOLDS',
                      'EDI',
                      'ENDPROCESS',
                      'HMS-PAGE',
                      'HMS-RETURN',
                      'HV-TRANS',
                      'ILL',
                      'ILL-OFFICE',
                      'INPROCESS',
                      'INSHIPPING',
                      'INTRANSIT',
                      'LAW-BIND',
                      'LOST-ASSUM',
                      'LOST-CLAIM',
                      'LOST-PAID',
                      'MISSING',
                      'MISS-INPRO',
                      'ON-ORDER',
                      'PAGE-ILL',
                      'PAGE-JA',
                      'PAGE-LN',
                      'PAGE-RLCP',
                      'PGDFROMSAL',
                      'PUB-TECH',
                      'REPAIR',
                      # removing SAL-PAGE from unavailable locations per Vitus' request
                      # "SAL-PAGE",
                      'SAL-RETURN',
                      'SEE-ARCHIV',
                      'SEE-EASTA',
                      'SPEC-INPRO',
                      'SUL-BIND',
                      'SULBIND-WA',
                      'TECH-ACQ',
                      'TECH-CAT',
                      'TECH-CONS',
                      'TECH-PROC',
                      'TECH-SER',
                      'TECH-SERV',
                      'TEMP-LL']

  CURRENT_HOME_LOCS = [
    'ART-AT-ENG',
    'ART-RESV',
    'BIO-RESV',
    'BUS-RESV',
    'BRAN-RESV',
    'CHEM-RESV',
    # "E-RESV", We need to figure out what to do w/ the pseudo eReserve library before enabling this
    'EARTH-RESV',
    'EAS-RESV',
    'EDU-RESV',
    'ENG-RESV',
    'GREEN-RESV',
    'GSB-RESV',
    'HAS-NEWBK',
    'HOOV-RESV',
    'HOP-RESV',
    'IC-DISPLAY',
    'LANE-RESV',
    'LANG-RESV',
    'LAW-RESV',
    'LOAN-DESK',
    'MATH-RESV',
    'MEDIA-RESV',
    'MEYER-RESV',
    'MUSIC-RESV',
    'PHYS-RESV',
    'RESV-DESKS',
    'RESERVES',
    'TANN-RESV',
    'SCI-RESV',
    'SSRC-NEWBK'
  ]

  RESERVE_DESKS = {
    'ART-RESV' => 'ART',
    'BUS-RESV' => 'BUSINESS',
    'E-RESV' => 'SW-E-RESV',
    'EARTH-RESV' => 'EARTH-SCI',
    'EAS-RESV' => 'EAST-ASIA',
    'EDU-RESV' => 'EDUCATION',
    'ENG-RESV' => 'ENG',
    'GREEN-RESV' => 'GREEN',
    'HOOV-RESV' => 'HOOVER',
    'HOP-RESV' => 'HOPKINS',
    'LAW-RESV' => 'LAW',
    'MEDIA-RESV' => 'MEDIA-MTXT',
    'MUSIC-RESV' => 'MUSIC',
    'SCI-RESV' => 'SCIENCE',
    'TANN-RESV' => 'TANNER'
  }

  HIDE_1ST_IND = %w(760 762 765 767 770 772 773 774 775 776 777 780 785 786 787)
  HIDE_1ST_IND0 = %w(541 542 561 583 590)
  CONTACT_INFO = {
    email: 'infocenter@stanford.edu',
    website: { label: 'SearchWorks', url: 'https://searchworks.stanford.edu' },
    libraries: [
      ['Green Library', '650 725 1064'],
      ['Meyer Library (Academic Computing)', '650 723 2434'],
      ['Green Library', '650 725 1064'],
      ['Art & Architecture Library', '650 723 3408'],
      ['Biology Library (Falconer)', '650 723 1528'],
      ['Business Library', '650 723 2162'],
      ['Chemistry and Chemical Engineering Library (Swain)', '650 723 9237'],
      ['Classics Library', '650 723 0479'],
      ['Earth Sciences Library (Branner)', '650 723 2746'],
      ['East Asia Library', '650 725 3435'],
      ['Education Library (at SAL1&2)', '650 723 2121'],
      ['Engineering Library (Terman)', '650 723 0001'],
      ['Hoover Institution Library', '650 723 2058'],
      ['Hoover Institution Archives', '650 723 3563'],
      ['Law Library (Crown)', '650 723 2477'],
      ['Map Collections (Branner Library)', '650 725 1103'],
      ['Marine Biology Library (Miller at Hopkins Marine Station)', '831 655 6229'],
      ['Math & Statistics Library', '650 723 4672'],
      ['Medical Library (Lane)', '650 723 6831'],
      ['Music Library', '650 723 1211'],
      ['Archive of Recorded Sound', '650 723 9312'],
      ['Philosophy Library (Tanner)', '650 723 1539'],
      ['Science Library (Li and Ma)', '650 723 1528'],
      ['Special Collections', '650 725 1022'],
      ['Stanford Auxiliary Library (SAL1&2)', '650 723 9201'],
      ['SLAC National Accelerator Laboratory Library', '650 926 2411']
    ]
    # No Physics or Meyer (ACOMP) in doc provided, the show up on web
  }

  EXCLUDE_FIELDS = ['w', '0', '1', '2', '5', '6', '8', '?', '=']

  NIELSEN_TAGS = { '505' => '905', '520' => '920', '586' => '986' }
  SOURCES = {
    'Nielsen' => '(source: Nielsen Book Data)',
    'AuxAmateurs' => '(source: Amalivre)'
  }
  SUL_ICONS = {
    'Object' => 'cube',
    'Academic Journal' => 'book-2',
    'Archive/Manuscript' => 'document-box-1',
    'Archived website' => 'network-web',
    'Article' => 'text-wrapping-1',
    'Book' => 'book-1',
    'Dataset' => 'business-chart-1',
    'Database' => 'window-search',
    'Equipment' => 'plug-2',
    'Image' => 'photos-1',
    'Journal/Periodical' => 'book-2',
    'Map' => 'map-location',
    'Music recording' => 'gramophone',
    'Music score' => 'file-music',
    'Newspaper' => 'newspaper-2',
    'Software/Multimedia' => 'mouse-2',
    'Sound recording' => 'microphone-2',
    'Video' => 'film-2',
    'Credits' => 'contacts-1',
    'Subjects' => 'tags-1',
    'Contents' => 'list-4',
    'Browse' => 'books-3',
    'Chat' => 'bubble-2',
    'Feedback' => 'mail-1',
    'Cite' => 'quote',
    'Send To' => 'link',
    'Selections' => 'check-3'
  }
  BROWSABLE_CALLNUMBERS = %w(LC DEWEY ALPHANUM)

  LIBRARY_INSTRUCTIONS = {
    'EDUCATION' => {
      heading: 'Access',
      text: 'The Education Library is closed for construction. Request items for pickup at another library.'
    },
    'HILA' => {
      heading: 'Access',
      text: 'Items must be requested in advance and viewed on-site.'
    },
    'HOOVER' => {
      heading: 'Access',
      text: 'Items must be requested in advance and viewed on-site.'
    },
    'HV-ARCHIVE' => {
      heading: 'Access',
      text: 'Items must be requested in advance and viewed on-site.'
    },
    'RUMSEY-MAP' => {
      heading: 'On-site access',
      text: 'Researchers can request to view these materials in the David Rumsey Map Center.'
    },
    'RUMSEYMAP' => {
      heading: 'On-site access',
      text: 'Researchers can request to view these materials in the David Rumsey Map Center.'
    },
    'SPEC-COLL' => {
      heading: 'On-site access',
      # text: 'Researchers can request to view these materials in the Special Collections Reading Room. Request materials at least 2 business days in advance. Maximum 5 items per day.'
      # Temporary message via https://github.com/sul-dlss/SearchWorks/issues/3235
      text: 'Collections are moving, which may affect access. Request materials as early as possible. Maximum 5 items per day. Contact specialcollections@stanford.edu for information about access.'
    }
  }.freeze
end
