module Constants
  UNKNOWN_LOCS = ['ASK@EASIA', 'ASK@GSB', 'ASK@LANE', 'CHECKSHELF', 'SEE-OTHER', 'STACKS-BW']
  PAGE_LOCS = ['BIO-TEMP', 'EALSAL-CHN', 'EALSAL-JPN', 'EALSAL-KOR', 'L-PAGE-EA', 'MATH-TEMP', 'MEDIA-30', 'MEDIAX-30', 'MSS-30', 'PAGE-BU', 'PAGE-LP', 'PAGE-MP', 'PAGE-IRON', 'SAL-ARABIC', 'SAL-FOLIO', 'SAL-LOAN', 'SAL-MUSIC', 'SAL-SERG', 'SAL-TEMP', 'SALTURKISH', 'STACKS-30']
  RELATOR_TERMS = { 'acp' => 'Art copyist',
                    'act' => 'Actor',
                    'adp' => 'Adapter',
                    'aft' => 'Author of afterword, colophon, etc.',
                    'anl' => 'Analyst',
                    'anm' => 'Animator',
                    'ann' => 'Annotator',
                    'ant' => 'Bibliographic antecedent',
                    'app' => 'Applicant',
                    'aqt' => 'Author in quotations or text abstracts',
                    'arc' => 'Architect',
                    'ard' => 'Artistic director ',
                    'arr' => 'Arranger',
                    'art' => 'Artist',
                    'asg' => 'Assignee',
                    'asn' => 'Associated name',
                    'att' => 'Attributed name',
                    'auc' => 'Auctioneer',
                    'aud' => 'Author of dialog',
                    'aui' => 'Author of introduction',
                    'aus' => 'Author of screenplay',
                    'aut' => 'Author',
                    'bdd' => 'Binding designer',
                    'bjd' => 'Bookjacket designer',
                    'bkd' => 'Book designer',
                    'bkp' => 'Book producer',
                    'bnd' => 'Binder',
                    'bpd' => 'Bookplate designer',
                    'bsl' => 'Bookseller',
                    'ccp' => 'Conceptor',
                    'chr' => 'Choreographer',
                    'clb' => 'Collaborator',
                    'cli' => 'Client',
                    'cll' => 'Calligrapher',
                    'clt' => 'Collotyper',
                    'cmm' => 'Commentator',
                    'cmp' => 'Composer',
                    'cmt' => 'Compositor',
                    'cng' => 'Cinematographer',
                    'cnd' => 'Conductor',
                    'cns' => 'Censor',
                    'coe' => 'Contestant -appellee',
                    'col' => 'Collector',
                    'com' => 'Compiler',
                    'cos' => 'Contestant',
                    'cot' => 'Contestant -appellant',
                    'cov' => 'Cover designer',
                    'cpc' => 'Copyright claimant',
                    'cpe' => 'Complainant-appellee',
                    'cph' => 'Copyright holder',
                    'cpl' => 'Complainant',
                    'cpt' => 'Complainant-appellant',
                    'cre' => 'Creator',
                    'crp' => 'Correspondent',
                    'crr' => 'Corrector',
                    'csl' => 'Consultant',
                    'csp' => 'Consultant to a project',
                    'cst' => 'Costume designer',
                    'ctb' => 'Contributor',
                    'cte' => 'Contestee-appellee',
                    'ctg' => 'Cartographer',
                    'ctr' => 'Contractor',
                    'cts' => 'Contestee',
                    'ctt' => 'Contestee-appellant',
                    'cur' => 'Curator',
                    'cwt' => 'Commentator for written text',
                    'dfd' => 'Defendant',
                    'dfe' => 'Defendant-appellee',
                    'dft' => 'Defendant-appellant',
                    'dgg' => 'Degree grantor',
                    'dis' => 'Dissertant',
                    'dln' => 'Delineator',
                    'dnc' => 'Dancer',
                    'dnr' => 'Donor',
                    'dpc' => 'Depicted',
                    'dpt' => 'Depositor',
                    'drm' => 'Draftsman',
                    'drt' => 'Director',
                    'dsr' => 'Designer',
                    'dst' => 'Distributor',
                    'dtc' => 'Data contributor ',
                    'dte' => 'Dedicatee',
                    'dtm' => 'Data manager ',
                    'dto' => 'Dedicator',
                    'dub' => 'Dubious author',
                    'edt' => 'Editor',
                    'egr' => 'Engraver',
                    'elg' => 'Electrician ',
                    'elt' => 'Electrotyper',
                    'eng' => 'Engineer',
                    'etr' => 'Etcher',
                    'exp' => 'Expert',
                    'fac' => 'Facsimilist',
                    'fld' => 'Field director ',
                    'flm' => 'Film editor',
                    'fmo' => 'Former owner',
                    'fpy' => 'First party',
                    'fnd' => 'Funder',
                    'frg' => 'Forger',
                    'gis' => 'Geographic information specialist ',
                    'grt' => 'Graphic technician',
                    'hnr' => 'Honoree',
                    'hst' => 'Host',
                    'ill' => 'Illustrator',
                    'ilu' => 'Illuminator',
                    'ins' => 'Inscriber',
                    'inv' => 'Inventor',
                    'itr' => 'Instrumentalist',
                    'ive' => 'Interviewee',
                    'ivr' => 'Interviewer',
                    'lbr' => 'Laboratory ',
                    'lbt' => 'Librettist',
                    'ldr' => 'Laboratory director ',
                    'led' => 'Lead',
                    'lee' => 'Libelee-appellee',
                    'lel' => 'Libelee',
                    'len' => 'Lender',
                    'let' => 'Libelee-appellant',
                    'lgd' => 'Lighting designer',
                    'lie' => 'Libelant-appellee',
                    'lil' => 'Libelant',
                    'lit' => 'Libelant-appellant',
                    'lsa' => 'Landscape architect',
                    'lse' => 'Licensee',
                    'lso' => 'Licensor',
                    'ltg' => 'Lithographer',
                    'lyr' => 'Lyricist',
                    'mcp' => 'Music copyist',
                    'mfr' => 'Manufacturer',
                    'mdc' => 'Metadata contact',
                    'mod' => 'Moderator',
                    'mon' => 'Monitor',
                    'mrk' => 'Markup editor',
                    'msd' => 'Musical director',
                    'mte' => 'Metal-engraver',
                    'mus' => 'Musician',
                    'nrt' => 'Narrator',
                    'opn' => 'Opponent',
                    'org' => 'Originator',
                    'orm' => 'Organizer of meeting',
                    'oth' => 'Other',
                    'own' => 'Owner',
                    'pat' => 'Patron',
                    'pbd' => 'Publishing director',
                    'pbl' => 'Publisher',
                    'pdr' => 'Project director',
                    'pfr' => 'Proofreader',
                    'pht' => 'Photographer',
                    'plt' => 'Platemaker',
                    'pma' => 'Permitting agency',
                    'pmn' => 'Production manager',
                    'pop' => 'Printer of plates',
                    'ppm' => 'Papermaker',
                    'ppt' => 'Puppeteer',
                    'prc' => 'Process contact',
                    'prd' => 'Production personnel',
                    'prf' => 'Performer',
                    'prg' => 'Programmer',
                    'prm' => 'Printmaker',
                    'pro' => 'Producer',
                    'prt' => 'Printer',
                    'pta' => 'Patent applicant',
                    'pte' => 'Plaintiff -appellee',
                    'ptf' => 'Plaintiff',
                    'pth' => 'Patent holder',
                    'ptt' => 'Plaintiff-appellant',
                    'rbr' => 'Rubricator',
                    'rce' => 'Recording engineer',
                    'rcp' => 'Recipient',
                    'red' => 'Redactor',
                    'ren' => 'Renderer',
                    'res' => 'Researcher',
                    'rev' => 'Reviewer',
                    'rps' => 'Repository',
                    'rpt' => 'Reporter',
                    'rpy' => 'Responsible party',
                    'rse' => 'Respondent-appellee',
                    'rsg' => 'Restager',
                    'rsp' => 'Respondent',
                    'rst' => 'Respondent-appellant',
                    'rth' => 'Research team head',
                    'rtm' => 'Research team member',
                    'sad' => 'Scientific advisor',
                    'sce' => 'Scenarist',
                    'scl' => 'Sculptor',
                    'scr' => 'Scribe',
                    'sds' => 'Sound designer',
                    'sec' => 'Secretary',
                    'sgn' => 'Signer',
                    'sht' => 'Supporting host',
                    'sng' => 'Singer',
                    'spk' => 'Speaker',
                    'spn' => 'Sponsor',
                    'spy' => 'Second party',
                    'srv' => 'Surveyor',
                    'std' => 'Set designer',
                    'stl' => 'Storyteller',
                    'stm' => 'Stage manager',
                    'stn' => 'Standards body',
                    'str' => 'Stereotyper',
                    'tcd' => 'Technical director',
                    'tch' => 'Teacher',
                    'ths' => 'Thesis advisor',
                    'trc' => 'Transcriber',
                    'trl' => 'Translator',
                    'tyd' => 'Type designer',
                    'tyg' => 'Typographer',
                    'vdg' => 'Videographer',
                    'voc' => 'Vocalist',
                    'wam' => 'Writer of accompanying material',
                    'wdc' => 'Woodcutter',
                    'wde' => 'Wood -engraver',
                    'wit' => 'Witness' }
  LOCS = {
    '13TH-FLOOR' => '13th floor',
    '15TH-FLOOR' => '15th floor',
    '1ST-FLOOR' => 'Ask at circulation desk',
    '2ND-FLOOR' => 'Ask at circulation desk',
    '2NDFLR-REF' => 'Ask at circulation desk',
    '3RD-FLOOR' => 'Ask at circulation desk',
    '3RDFLR-REF' => 'Ask at circulation desk',
    'ACAD-DATA' => 'Social Science Data and Software',
    'ARABIC' => 'Arabic',
    'ARS-LOAN' => 'In Archive of Recorded Sound: Ask at service desk',
    'ART-AT-ENG' => 'Currently at Terman Library',
    'ART-LOAN' => 'At Art Library circulation desk',
    'ART-RESV' => 'On reserve at Art Library',
    'ARTLCKL' => 'Locked stacks (Large): Ask at circulation desk',
    'ARTLCKL-R' => 'Locked stacks (Large): Ask at circulation desk. (Permission required from Art Librarian.)',
    'ARTLCKM' => 'Locked stacks (Medium): Ask at circulation desk',
    'ARTLCKM-R' => 'Locked stacks (Medium): Ask at circulation desk. (Permission required from Art Librarian.)',
    'ARTLCKO' => 'Locked stacks (Oversize): Ask at circulation desk',
    'ARTLCKO-R' => 'Locked stacks (Oversize): Ask at circulation desk. (Permission required from Art Librarian.)',
    'ARTLCKS' => 'Locked stacks (Small): Ask at circulation desk',
    'ARTLCKS-R' => 'Locked stacks (Small): Ask at circulation desk. (Permission required from Art Librarian.)',
    'ARTVAULT' => 'Art Vault',
    'ASK@EASIA' => 'Ask at circulation desk',
    'ASK@GSB' => 'Check Business Library catalog for status',
    'ASK@LANE' => 'Check Lane Library catalog for status',
    'ASSMD-LOST' => 'Checked out - Overdue',
    'AT-REPAIR' => 'Out for repair',
    'ATCIRCDESK' => 'Ask at circulation desk',
    'ATLASES' => 'Atlas Section',
    'AVAIL_SOON' => 'Ask at circulation desk',
    'B&F-HOLD' => 'At bindery',
    'BARCHAS' => 'Barchas Collection',
    'BASEMENT' => 'Basement',
    'BASEMNT' => 'Basement',
    'BENDER' => 'Bender Room',
    'BIB-INDEX' => 'Bibliographies & Indexes section',
    'BILLED-OD' => 'Overdue',
    'BINDERY' => 'At bindery',
    'BIO-LOAN' => 'At Falconer Library circulation desk',
    'BIO-RESV' => 'On reserve at Falconer Library',
    'BIO-TEMP' => 'Ask at circulation desk',
    'BOX-COLL' => 'Box Collection',
    'BRAN-RESV' => 'On reserve at Branner Library',
    'BRIT-DOCS' => 'British Government Documents',
    'BUS-ARCH' => 'Archives: Ask at i-Desk',
    'BUS-CMC' => 'Career Corner',
    'BUS-COMPF' => 'Computer files: Ask at i-Desk',
    'BUS-LOAN' => 'At Business Library i-Desk',
    'BUS-LOCKED' => 'Locked stacks: Ask at i-Desk',
    'BUS-MAKENA' => 'Makena Capital Traders Pit',
    'BUS-PER' => 'Periodicals',
    'BUS-POP' => 'Popular Business Books',
    'BUS-RESV' => 'On reserve at Business Library',
    'BUS-STACKS' => 'Stacks',
    'BUS-TEMP' => 'Ask at i-Desk',
    'BUSDISPLAY' => 'Display shelves',
    'CALIF-DOCS' => 'California State Documents',
    'CASE-MP' => 'Request for use at Map Center (case map)',
    'CCRMA' => 'Ask at circulation desk',
    'CDL-2NDFL' => 'Ask at circulation desk',
    'CDP' => 'Ask at circulation desk',
    'CDP-CHI' => 'Ask at circulation desk',
    'CDP-GER' => 'Ask at circulation desk',
    'CDP-JUDA' => 'Ask at circulation desk',
    'CDP-LAT' => 'Ask at circulation desk',
    'CDP-ROM' => 'Ask at circulation desk',
    'CDP-SLAV' => 'Ask at circulation desk',
    'CHE-LOAN' => 'At Swain Library circulation desk',
    # 'CHECKEDOUT' => 'Checked out - Due <date>',
    'CHECKSHELF' => 'Check shelf',
    'CHEM-RESV' => 'On reserve at Swain Library',
    'CHINESE' => 'Chinese Collection',
    'CHKD-OUT-D' => 'Ask at circulation desk',
    'COLL-WORKS' => 'Storage area: Collected Works section',
    'COMPACT' => 'Ask at circulation desk',
    'COURSE-RES' => 'Ask at circulation desk',
    'COURSE-VID' => 'Ask at circulation desk',
    'CPM-HOLDS' => 'At bindery',
    'CROTHERS' => 'Crothers Collection',
    'CURRENTPER' => 'Current periodicals',
    'CURRICULUM' => 'Curriculum Collection',
    'CURRSTOR' => 'Ask at circulation desk',
    'DOMESTIC' => 'Domestic',
    'EAL-SETS' => 'East Asia Big Sets',
    'EAL-STKS-C' => 'Chinese Collection',
    'EAL-STKS-J' => 'Japanese Collection',
    'EAL-STKS-K' => 'Korean Collection',
    'EALSAL-CHN' => 'Ask at circulation desk',
    'EALSAL-JPN' => 'Ask at circulation desk',
    'EALSAL-KOR' => 'Ask at circulation desk',
    'EAR-LOAN' => 'At Branner Library circulation desk',
    'EARTH-RESV' => 'On reserve at Branner Library',
    'EAS-LOAN' => 'At East Asia Library circulation desk',
    'EAS-RESV' => 'On reserve at East Asia Library',
    'EDI' => 'In process',
    'EDU-LOAN' => 'At Cubberley Library circulation desk',
    'EDU-RESV' => 'On reserve at Cubberley Library',
    'ENDPROCESS' => 'In process',
    'ENG-LOAN' => 'At Terman Library circulation desk',
    'ENG-RESV' => 'On reserve at Terman Library',
    'ENGDISPLAY' => 'Magazine display (latest issues only)',
    'EQUIPMENT' => 'Equipment: Ask at circulation desk',
    'EXPEDITION' => 'Expedition: Locked Stacks',
    'EYLESAISLE' => 'Eyles aisle',
    'FACULTY' => 'Faculty',
    'FED-DOCS' => 'US Federal Documents',
    'FELT-STOR' => 'Felton Collection',
    'FELTON' => 'Felton Collection',
    'FELTON-30' => 'Felton Collection',
    'FOLIO' => 'Folios',
    'FOLIO-3RD' => 'Folios on the 3rd floor',
    'FOLIO-BAS' => 'Folios in the basement',
    'FOLIO-CHN' => 'Chinese Folios',
    'FOLIO-FLAT' => 'Flat folios',
    'FOLIO-JPN' => 'Japanese Folios',
    'FOLIO-KOR' => 'Korean Folios',
    'FOREIGN' => 'Foreign Government Documents',
    'FORN-DOCS' => 'Foreign Government Documents',
    'FRECOT' => 'Frecot Collection',
    'GADGETBAR' => 'Gadget Bar',
    'GOLDSTAR' => 'Ask at circulation desk',
    'GRE-LOAN' => 'At Green Library circulation desk',
    'GREEN-RESV' => 'On reserve at Green Library',
    'GSB-RESV' => 'On reserve at Business Library',
    'GUNST' => 'Gunst Collection',
    'GUNST-30' => 'Gunst Collection',
    'GUNST-STOR' => 'Gunst Collection',
    'HAS-ATLAS' => 'Lane Reading Room: Atlases',
    'HAS-CA' => 'Lane Reading Room: California history',
    'HAS-DIGIT' => 'Lane Reading Room: Digital culture and humanities computing',
    'HAS-FIC' => 'Lane Reading Room: Recent fiction',
    'HAS-FOLIO' => 'Lane Reading Room: Oversize books',
    'HAS-JOURN' => 'Lane Reading Room: Journals',
    'HAS-LIT' => 'Lane Reading Room',
    'HAS-NEWBK' => 'Lane Reading Room: New books',
    'HAS-RR' => 'Lane Reading Room: Ready reference',
    'HAS-SU' => 'Lane Reading Room: Stanford history',
    'HASRC' => 'Lane Reading Room: Reference',
    'HMS-PAGE' => 'In transit to main campus',
    'HMS-RETURN' => 'In transit to Hopkins',
    'HOLDS' => 'Ask at circulation desk',
    'HOO-LOAN' => 'At Hoover Library circulation desk',
    'HOOV-RESV' => 'On reserve at Hoover Library',
    'HOP-LOAN' => 'At Miller Library circulation desk',
    'HOP-RESV' => 'On reserve at Miller Library',
    'HV-TRANS' => 'In transit',
    'HVA-LOAN' => 'At Hoover Archives circulation desk',
    'HY-PAGE-EA' => 'Harvard-Yenching Collection: Must be picked up at East Asia Library',
    'IC' => 'Information Center',
    'IC-ATLAS' => 'Information Center: Atlases',
    'IC-CDROM' => 'Information Center: CDROMs',
    'IC-DESK' => 'Information Center desk',
    'IC-DISPLAY' => 'Information Center display',
    'IC-EXHIBIT' => 'Information Center exhibit',
    'IC-NEWS' => 'Information Center: Newspapers',
    'IC-RREF' => 'Information Center: Reference',
    'IC-STATS' => 'Information Center: Statistics',
    'ILB-LOAN' => 'Ask at circulation desk',
    'ILL' => 'Ask at circulation desk',
    'ILL-OFFICE' => 'Ask at circulation desk',
    'INDEXES' => 'Indexes',
    'INPROCESS' => 'In process',
    'INSHIPPING' => 'In process',
    'INSTRUCTOR' => "Instructor's copy",
    'INTCOLLCAT' => 'International college catalogs',
    'INTERNET' => 'Online resource',
    'INTL-DOCS' => 'International Government Documents',
    'INTRANSIT' => 'In transit',
    'JAPANESE' => 'Japanese Collection',
    'KOREAN' => 'Korean Collection',
    'L-PAGE-EA' => 'Request for use in East Asia Library',
    'LAC' => 'In process',
    'LANE-RESV' => 'On reserve at Lane Library',
    'LANG-LAB' => 'Language Lab',
    'LANG-RESV' => 'Language Lab reserves',
    'LAW-ARCHIV' => 'Archives: Ask at circulation desk',
    'LAW-BIND' => 'At bindery',
    'LAW-CAREER' => 'Ask at circulation desk',
    'LAW-CIRC' => 'At Law Library circulation desk',
    'LAW-LOAN' => 'At Law Library circulation desk',
    'LAW-RESV' => 'On reserve at Law Library',
    'LAW-REVIEW' => 'Law Review',
    'LAW-SPEC' => 'Law Collection',
    'LCK-STOR' => 'Locked storage: Ask at circulation desk',
    'LCKBYTITL' => 'Locked Stacks: ask at circulation desk',
    'LEWIS-COLL' => 'Lewis Collection',
    'LOAN-DESK' => 'Ask at circulation desk',
    'LOCK-CHN' => 'Locked stacks: Ask at circulation desk',
    'LOCK-HOLDS' => 'Locked stacks: Ask at circulation desk',
    'LOCK-JPN' => 'Locked stacks: Ask at circulation desk',
    'LOCK-KOR' => 'Locked stacks: Ask at circulation desk',
    'LOCKED-DIS' => 'Locked stacks: Ask at circulation desk',
    'LOCKED-MAP' => 'Locked map files: Ask at circulation desk',
    'LOCKED-STK' => 'Locked stacks: Ask at circulation desk',
    'LOST-ASSUM' => 'Checked out - Overdue',
    'LOST-CLAIM' => 'Lost',
    'LOST-PAID' => 'Lost',
    'MANNING' => 'Manning Collection',
    'MANUSCRIPT' => 'Manuscript Collection',
    'MAP-CASES' => 'Map cases',
    'MAP-FILE' => 'Map files',
    'MAP-REF' => 'Reference maps',
    'MAP-STOR' => 'Map storage: Ask at circulation desk',
    'MAPS' => 'Maps',
    'MAT-LOAN' => 'At Math & Statistics Library circulation desk',
    'MATH-ARCH' => 'Ask at circulation desk',
    'MATH-RESV' => 'On reserve at Math & Statistics Library',
    'MATH-TECH' => 'Ask at circulation desk',
    'MATH-TEMP' => 'Ask at circulation desk',
    'MEDIA' => 'Media',
    'MEDIA-30' => 'Media',
    'MEDIA-MTXT' => 'Media & Microtext Center',
    'MEDIA-RESV' => 'On reserve at Media & Microtext Center',
    'MEDIAX' => 'Media Collection',
    'MEDIAX-30' => 'Media Collection',
    'MEDIEVALRM' => 'Medieval Studies (Raubitschek) Room',
    'MEMLIBMUS' => 'Memorial Library of Music',
    'MEY-LOAN' => 'Ask at circulation desk',
    'MEYER-RESV' => 'Ask at circulation desk',
    'MEZZANINE' => 'Mezzanine',
    'MICROFICHE' => 'Microfiche',
    'MICROFILM' => 'Microfilm',
    'MICROTEXT' => 'Microtext',
    'MINIATURE' => 'Miniature',
    'MISS-INPRO' => 'Missing',
    'MISSING' => 'Missing',
    'MM-ARTCAB' => 'Microfiche collection B',
    'MM-BUSCAB' => 'Microfiche collection A',
    'MM-DIZOCAB' => 'Microfiche collection D',
    'MM-MATHCAB' => 'Microfiche collection C',
    'MM-CDCAB' => 'Ask at Media Microtext desk',
    'MM-CMPACT2' => 'Ask at Media Microtext desk',
    'MM-OVERSIZ' => 'Ask at Media Microtext desk',
    'MM-STACKS' => 'Ask at Media Microtext desk',
    'MP-CASE-LG' => 'Request for use at Map Center (large case)',
    'MP-CASE-MD' => 'Request for use at Map Center (medium case)',
    'MP-CASE-SM' => 'Request for use at Map Center (small case)',
    'MSS-10' => 'Manuscript Collection',
    'MSS-20' => 'Manuscript Collection',
    'MSS-30' => 'Manuscript Collection',
    'MSSX' => 'Manuscript Collection',
    'MSSX-30' => 'Manuscript Collection',
    'MUS-LOAN' => 'At Music Library circulation desk',
    'MUS-NOCIRC' => 'Ask at circulation desk',
    'MUS-TXTBK' => 'Ask at circulation desk',
    'MUSIC-RESV' => 'On reserve at Music Library',
    'ND-PAGE-EA' => 'NDC Collection: Must be picked up in East Asia Library',
    'NEWBOOKS' => 'New books shelf',
    'NEWS-STKS' => 'Newspaper stacks',
    'NEWSPAPERS' => 'Newspapers',
    'NEWTON' => 'Newton Collection',
    'ON-ORDER' => 'On order',
    'OPEN-RES' => 'Open reserves',
    'OVERSIZED' => 'Oversized',
    'PAGE-AR' => 'Request for use in Art & Architecture Library  or Special Collections',
    'PAGE-AS' => 'Request for use in Archive of Recorded Sound',
    'PAGE-BI' => 'Request for use in Falconer Library',
    'PAGE-BU' => 'Request for pickup at Business Library',
    'PAGE-CH' => 'Request for use in Swain Library',
    'PAGE-CL' => 'Request for use in Classics Library',
    'PAGE-EA' => 'Request for use in East Asia Library',
    'PAGE-ED' => 'Request for use in Cubberley Library',
    'PAGE-EN' => 'Request for use in Terman Library',
    'PAGE-ES' => 'Request for use in Branner Library',
    'PAGE-GR' => 'Request for use in Green Library',
    'PAGE-HA' => 'Request for use in Hoover Archives',
    'PAGE-HP' => 'Request for use in Miller Library or Green Library',
    'PAGE-HV' => 'Request for use in Hoover Library',
    'PAGE-ILL' => 'Paged to Interlibrary Loan Department',
    'PAGE-IRON' => 'Offsite',
    'PAGE-JA' => 'Ask at circulation desk',
    'PAGE-LN' => 'Paged to Medical Library',
    'PAGE-LP' => 'Request for pickup at Music Library or Media & Microtext Center',
    'PAGE-LW' => 'Request for use in Law Library',
    'PAGE-MA' => 'Request for use in Math & Statistics Library',
    'PAGE-MD' => 'Request for use in Green Media & Microtext Center',
    'PAGE-MP' => 'Request for pickup at Branner Library',
    'PAGE-MU' => 'Request for use in Music Library',
    'PAGE-MY' => 'Ask at circulation desk',
    'PAGE-PH' => 'Ask at circulation desk',
    'PAGE-RLCP' => 'Ask at circulation desk',
    'PAGE-RM' => 'Request for use in David Rumsey Map Center',
    'PAGE-SP' => 'Request for use in Special Collections Reading Room',
    'PAGE-TA' => 'Request for use in Philosophy Library',
    'PERM-RES' => 'Permanent reserve: Ask at circulation desk',
    'PERSIAN' => 'Persian',
    'PGDFROMSAL' => 'In transit to campus library',
    'PHOTO-PERM' => 'Ask at circulation desk',
    'PHY-LOAN' => 'Ask at circulation desk',
    'PHYS-RESV' => 'Ask at circulation desk',
    'PHYSTEMP' => 'Currently online only',
    'POPSCI' => 'Popular science',
    'PUB-TECH' => 'Ask at circulation desk',
    'R-FOLIO' => 'Folio (Limited loan)',
    'R-FOLIO-FL' => 'Flat folio (Limited loan)',
    'R-MINIATUR' => 'Miniature (Limited loan)',
    'R-STACKS' => 'Stacks (Limited loan)',
    'RARE-BOOKS' => 'Rare Books Collection',
    'RARE-STOR' => 'Rare Books Collection',
    'RAUB-COLL' => 'Raubitschek Collection of Papyrology and Epigraphy',
    'RAUB-NUM' => 'Frank L. Kovacs Numismatic Library',
    'RBC-30' => 'Rare Books Collection',
    'RBCX' => 'Rare Books Collection',
    'RBCX-30' => 'Rare Books Collection',
    'READING-RM' => 'Reading Room',
    'READY-REF' => 'Reference',
    'RECORDINGS' => 'Recordings',
    'REF-CHN' => 'Reference',
    'REF-DESK' => 'Reference desk',
    'REF-JPN' => 'Reference',
    'REF-KOR' => 'Reference',
    'REF-SERIAL' => 'Reference',
    'REFERENCE' => 'Reference',
    'REPAIR' => 'Out for repair',
    'RESEARCH' => 'Research',
    'RESERVES' => 'Reserves',
    'RESV-DESKS' => 'Ask at circulation desk',
    'RET-REF' => 'Reference',
    'ROB-STOR' => 'Robinson Collection',
    'ROBINSON' => 'Robinson Collection',
    'RUM-LOAN' => 'In Map Center: Ask at service desk',
    'RUMSEY' => 'Rumsey Collection',
    'RUMSEYREF' => 'David Rumsey Map Center',
    'SAFETY' => 'Safety Collection',
    'SAL-ARABIC' => 'Temporary shelving for Arabic materials',
    'SAL-FOLIO' => 'Temporary shelving for Folio materials',
    'SAL-LOAN' => 'SAL1&2 circulation desk',
    'SAL-MUSIC' => 'Temporary shelving for Music materials',
    'SAL-PAGE' => 'Temporary shelving',
    'SAL-RETURN' => 'In transit to SAL1&2',
    'SAL-SERG' => 'Science and Engineering shelving at SAL',
    'SAL-TEMP' => 'Temporary shelving',
    'SALTURKISH' => 'Temporary shelving for Turkish materials',
    'SAMSON' => 'Samson Collection',
    'SCBS' => 'Stanford Center for Buddhist Studies (Bldg. 70)',
    'SCORES' => 'Scores',
    'SCI-LOAN' => 'At Li and Ma Science Library circulation desk',
    'SCI-RESV' => 'On reserve at Li and Ma Science Library',
    'SEE-ARCHIV' => 'Currently at Hoover Archives',
    'SEE-EASTA' => 'Ask at circulation desk',
    'SEE-LOAN' => 'Ask at circulation desk',
    'SEE-OTHER' => 'See related record(s) to request item',
    'SERIALS' => 'Serials',
    'SETS' => 'Big Sets',
    'SHELBYSER' => 'Serials',
    'SHELBYTITL' => 'Serials',
    'SL3-LOAN' => 'Ask at circulation desk',
    'SLN-LOAN' => 'Ask at circulation desk',
    'SOUTH-MEZZ' => 'Stacks',
    'SPE-LOAN' => 'In Reading Room: Ask at service desk',
    'SPEC-STOR' => 'In storage, not available',
    'SPECDESK' => 'In Reading Room: Ask at service desk',
    'SSRC' => 'Jonsson Social Sciences Reading Room',
    'SSRC-ANRPT' => 'Ask at circulation desk',
    'SSRC-ATLAS' => 'Jonsson Social Sciences Reading Room: Atlas stand',
    'SSRC-CLASS' => 'Jonsson Social Sciences Reading Room',
    'SSRC-CSLI' => 'Jonsson Social Sciences Reading Room',
    'SSRC-CURR' => 'Jonsson Social Sciences Reading Room',
    'SSRC-DATA' => 'Velma Denning Room (Social Science Data and Software)',
    'SSRC-DESK' => 'Jonsson Social Sciences Reading Room',
    'SSRC-DOCS' => 'Jonsson Social Sciences Reading Room: Atrium',
    'SSRC-FICHE' => 'Bing Wing lower level: Microform cabinets',
    'SSRC-FILM' => 'Bing Wing lower level: Microform cabinets',
    'SSRC-NEWBK' => 'Jonsson Social Sciences Reading Room: New books',
    'SSRC-NWDOC' => 'Ask at circulation desk',
    'SSRC-SLS' => 'Ask at circulation desk',
    'SSRC-SSDS' => 'Velma Denning Room (Social Science Data and Software)',
    'STACKS' => 'Stacks',
    'STACKS-1' => 'Stacks 1',
    'STACKS-2' => 'Stacks 2',
    'STACKS-3' => 'Stacks 3',
    'STACKS-30' => 'Stacks',
    'STACKS-BW' => 'Bound with another item',
    'STAFF' => 'Ask at circulation desk',
    'STK-GEMS' => 'Collection Gems',
    'STK-NOCIRC' => 'Stacks',
    'STK-SM' => 'Request for use at Map Center (small stacks)',
    'STK-MED' => 'Request for use at Map Center (medium stacks)',
    'STK-LG' => 'Request for use at Map Center (large stacks)',
    'STK-XLG' => 'Request for use at Map Center (x-large stacks)',
    'STKS1-NEW' => 'New books shelf',
    'STORAGE' => 'Ask at circulation desk',
    'STORBYTITL' => 'Storage area: Shelved by title',
    'STUDY-AIDS' => 'Study aids',
    'SUL-BIND' => 'At bindery',
    'SUL-LOAN' => 'Ask at circulation desk',
    'SULBIND-WA' => 'At bindery',
    'SW-E-RESERVE-DESK' => 'Online item on course reading list',
    'SW-RESERVE-DESK' => 'On reserve: Ask at circulation desk',
    'TAN-LOAN' => 'At Tanner Library circulation desk',
    'TANN-RESV' => 'On reserve at Tanner Library',
    'TAUBE' => 'Taube Collection',
    'TECH-ACQ' => 'In Tech Services',
    'TECH-CAT' => 'In Tech Services',
    'TECH-CONS' => 'In Tech Services',
    'TECH-DESK' => 'The Tech Desk',
    'TECH-PROC' => 'In Tech Services',
    'TECH-RPTS' => 'Technical Reports',
    'TECH-SER' => 'In Tech Services',
    'TECH-SERV' => 'In Tech Services',
    'TEMP-LL' => 'Ask at circulation desk',
    'TEMP-LOC' => 'Ask at circulation desk',
    'TERM-COLL' => 'Terman Collection: Ask at circulation desk',
    'THEA-STOR' => 'Theatre Collection',
    'THEATRE' => 'Theatre Collection',
    'THESES' => 'Theses',
    'TIMO-COLL' => 'Timoshenko Collection: Ask at circulation desk',
    'TINY' => 'Miniature',
    'TRES-LAIR' => 'Ask at circulation desk',
    'TURKISH' => 'Turkish',
    'U-ARCHIVES' => 'University Archives',
    'UARCH-30' => 'University Archives',
    'UARCH-REF' => 'University Archives reference',
    'UARCH-STOR' => 'University Archives',
    'UARCHX' => 'University Archives',
    'UARCHX-30' => 'University Archives',
    'UNCAT' => 'Ask at circulation desk',
    'UNDERGRAD' => 'Undergraduate Collection',
    'UNKNOWN' => 'Ask at circulation desk',
    'US-LOCAL' => 'US Local Documents',
    'US-STATE' => 'US State Documents',
    'VARIES' => 'Ask at circulation desk',
    'VAULT' => 'Vault',
    'VROOMAN' => 'Vrooman Collection',
    'W7-CASE-MP' => 'Request for use at Map Center (W7 case map)',
    'W7-CASE-MT' => 'Request for use at Map Center (W7 matted maps)',
    'W7-CASE-MD' => 'Request for use at Map Center (W7 map case)',
    'W7-MAP-BXS' => 'Request for use at Map Center (W7 small box)',
    'W7-MAP-BXL' => 'Request for use at Map Center (W7 large box)',
    'W7-POCK-LG' => 'Request for use at Map Center (W7 large pocket maps)',
    'W7-POCK-RG' => 'Request for use at Map Center (W7 regular pocket maps)',
    'W7-ROLLED' => 'Request for use at Map Center (W7 rolled)',
    'W7-SANBORN' => 'Request for use at Map Center (W7 Sanborn case)',
    'W7-STK-SM' => 'Request for use at Map Center (W7 small stacks)',
    'W7-STK-MED' => 'Request for use at Map Center (W7 medium stacks)',
    'W7-STK-LG' => 'Request for use at Map Center (W7 large stacks)',
    'W7-STK-XLG' => 'Request for use at Map Center (W7 x-large stacks)',
    'W7-STORAGE' => 'Request for use at Map Center (W7 storage)',
    'W7-OBJECTS' => 'Request for use at Map Center (W7 objects)',
    'W7-FOLIO' => 'Request for use at Map Center (W7 folios)',
    'W7-REF' => 'Request for use at Map Center (W7 reference)',
    'W7-STAFF' => 'Request for use at Map Center (W7 staff)',
    'W7-STFSHD' => 'Request for use at Map Center (W7 shadowed)',
    'W7-FRAME' => 'Request for use at Map Center (W7 framed)',
    'W7-POCKET' => 'Request for use at Map Center (W7 pocket)',
    'WEST-7B' => 'Ask at circulation desk'
  }.freeze

  NONCIRC_LOCS = ['2NDFLR-REF',
                  '3RDFLR-REF',
                  'ARTLCKL-R',
                  'ARTLCKM-R',
                  'ARTLCKO-R',
                  'ARTLCKS-R',
                  'ARTLCKL',
                  'ARTLCKM',
                  'ARTLCKO',
                  'ARTLCKS',
                  'ARTVAULT',
                  'BARCHAS',
                  'BENDER',
                  'BUS-ARCH',
                  'BUS-COMPF',
                  'BUS-LOCKED',
                  'BUS-MAKENA',
                  'BUSDISPLAY',
                  'ENGDISPLAY',
                  'FACULTY',
                  'FELTON',
                  'FELT-STOR',
                  'FRECOT',
                  'GUNST',
                  'GUNST-30',
                  'GUNST-STOR',
                  'HAS-ATLAS',
                  'HAS-CA',
                  'HAS-FOLIO',
                  'HAS-JOURN',
                  'HAS-LIT',
                  'HASRC',
                  'HAS-RR',
                  'HAS-SU',
                  'IC',
                  'IC-ATLAS',
                  'IC-CDROM',
                  'IC-DESK',
                  'IC-NEWS',
                  'IC-RREF',
                  'IC-STATS',
                  'LAW-SPEC',
                  'LOCK-CHN',
                  'LOCK-JPN',
                  'LOCK-KOR',
                  'MANNING',
                  'MEDIEVALRM',
                  'MEMLIBMUS',
                  'MICROFICHE',
                  'MM-ARTCAB',
                  'MM-BUSCAB',
                  'MM-DIZOCAB',
                  'MM-MATHCAB',
                  'MUS-NOCIRC',
                  'NEWS-STKS',
                  'NEWSPAPERS',
                  'NEWTON',
                  'RARE-BOOKS',
                  'RARE-STOR',
                  'RAUB-COLL',
                  'RAUB-NUM',
                  'RBCX',
                  'REF-CHN',
                  'REF-DESK',
                  'REFERENCE',
                  'REF-JPN',
                  'REF-KOR',
                  'REF-SERIAL',
                  'RET-REF',
                  'ROBINSON',
                  'ROB-STOR',
                  'RUMSEY',
                  'SAFETY',
                  'SAL-TEMP',
                  'SCBS',
                  'SSRC',
                  'SSRC-ANRPT',
                  'SSRC-ATLAS',
                  'SSRC-CURR',
                  'SSRC-DATA',
                  'SSRC-DESK',
                  'SSRC-DOCS',
                  'SSRC-FICHE',
                  'SSRC-FILM',
                  'SSRC-SSDS',
                  'STK-NOCIRC',
                  'STUDY-AIDS',
                  'TAUBE',
                  'TERM-COLL',
                  'THEA-STOR',
                  'THEATRE',
                  'TIMO-COLL']

  NONCIRC_PAGE_LOCS = ['FELTON-30',
                       'PAGE-AR',
                       'PAGE-AS',
                       'PAGE-BI',
                       'PAGE-CH',
                       'PAGE-CL',
                       'PAGE-EA',
                       'PAGE-ED',
                       'PAGE-EN',
                       'PAGE-ES',
                       'PAGE-GR',
                       'PAGE-HA',
                       'PAGE-HP',
                       'PAGE-HV',
                       'PAGE-LW',
                       'PAGE-MA',
                       'PAGE-MD',
                       'PAGE-MU',
                       'PAGE-MY',
                       'PAGE-PH',
                       'PAGE-RM',
                       'PAGE-SP',
                       'PAGE-TA',
                       'RBC-30',
                       'RBCX-30',
                       'UARCH-30',
                       'U-ARCHIVES',
                       'UARCH-REF',
                       'UARCH-STOR',
                       'UARCHX',
                       'UARCHX-30']

  UNAVAILABLE_LOCS = ['ASSMD-LOST',
                      'AT-REPAIR',
                      'AVAIL_SOON',
                      'B&F-HOLD',
                      'BILLED-OD',
                      'BINDERY',
                      # "CHECKEDOUT",
                      'CHKD-OUT-D',
                      'CPM-HOLDS',
                      'EDI',
                      'ENDPROCESS',
                      'HMS-PAGE',
                      'HMS-RETURN',
                      'HV-TRANS',
                      'ILL',
                      'ILL-OFFICE',
                      'INPROCESS',
                      'INSHIPPING',
                      'INTRANSIT',
                      'LAW-BIND',
                      'LOST-ASSUM',
                      'LOST-CLAIM',
                      'LOST-PAID',
                      'MISSING',
                      'MISS-INPRO',
                      'ON-ORDER',
                      'PAGE-ILL',
                      'PAGE-JA',
                      'PAGE-LN',
                      'PAGE-RLCP',
                      'PGDFROMSAL',
                      'PUB-TECH',
                      'REPAIR',
                      # removing SAL-PAGE from unavailable locations per Vitus' request
                      # "SAL-PAGE",
                      'SAL-RETURN',
                      'SEE-ARCHIV',
                      'SEE-EASTA',
                      'SUL-BIND',
                      'SULBIND-WA',
                      'TECH-ACQ',
                      'TECH-CAT',
                      'TECH-CONS',
                      'TECH-PROC',
                      'TECH-SER',
                      'TECH-SERV',
                      'TEMP-LL']

  REQUEST_LIBS = ['MEDIA-MTXT', 'RUMSEYMAP', 'SAL', 'SAL3', 'SAL-NEWARK', 'SPEC-COLL'].freeze

  LOCATION_LEVEL_REQUEST_LOCS = ['SSRC-DATA']

  REQUEST_ON_SITE_ACCESS_LIBS = [
    'HV-ARCHIVE',
    'RUMSEYMAP',
    'SPEC-COLL'
  ].freeze

  REQUEST_LOCS = ['GUNST-30',
                  'FELTON-30',
                  'RBC-30',
                  'RBCX-30',
                  'UARCH-30',
                  'UARCHX-30',
                  'MEDIA-30',
                  'MEDIAX-30',
                  'MSS-30',
                  'STACKS-30',
                  'AT-REPAIR',
                  'AVAIL_SOON',
                  'B&F-HOLD',
                  'BILLED-OD',
                  'BINDERY',
                  # "CHECKEDOUT",
                  'EDI',
                  'ENDPROCESS',
                  'INPROCESS',
                  'INSHIPPING',
                  'PAGE-IRON',
                  'PUB-TECH',
                  'REPAIR',
                  'SAL-RETURN',
                  'SUL-BIND',
                  'SULBIND-WA',
                  'TECH-ACQ',
                  'TECH-CAT',
                  'TECH-CONS',
                  'TECH-PROC',
                  'TECH-SER',
                  'TECH-SERV',
                  'TEMP-LL',
                  'MSSX-30']

  REQUESTABLE_CURRENT_LOCS = [
    'MISSING',
    'NEWBOOKS',
    'ON-ORDER'
  ]
  FORCE_AVAILABLE_CURRENT_LOCS = [
    'ART-AT-ENG',
    'IC-DISPLAY'
  ]

  FORCE_NONCIRC_CURRENT_LOCS = [
    'NEWBOOKS'
  ]

  UNAVAILABLE_CURRENT_LOCS = ['AT-REPAIR',
                              'AVAIL_SOON',
                              'B&F-HOLD',
                              'BILLED-OD',
                              'BINDERY',
                              # "CHECKEDOUT",
                              'CPM-HOLDS',
                              'ENDPROCESS',
                              'INPROCESS',
                              'INTRANSIT',
                              'LOST-ASSUM',
                              'MISSING',
                              'ON-ORDER',
                              'PUB-TECH',
                              'REPAIR',
                              'SAL-RETURN',
                              'SUL-BIND',
                              'SULBIND-WA',
                              'TECH-ACQ',
                              'TECH-CAT',
                              'TECH-CONS',
                              'TECH-PROC',
                              'TECH-SER',
                              'TECH-SERV',
                              'TEMP-LL']
  NON_REQUESTABLE_CURRENT_LOCS = [
    'ART-AT-ENG',
    'IC-DISPLAY',
    'LAC',
    'SEE-LOAN'
  ]
  NON_REQUESTABLE_HOME_LOCS = [
    'SEE-OTHER',
    'TECH-DESK'
  ]

  HIDE_DUE_DATE_CURRENT_LOCS = [
    'ART-AT-ENG',
    'IC-DISPLAY',
    'LOST-ASSUM',
    'LOST-CLAIM',
    'LOST-PAID',
    'NEWBOOKS',
    'SEE-LOAN'
  ]

  CURRENT_HOME_LOCS = [
    'ART-AT-ENG',
    'ART-RESV',
    'BIO-RESV',
    'BUS-RESV',
    'BRAN-RESV',
    'CHEM-RESV',
    # "E-RESV", We need to figure out what to do w/ the pseudo eReserve library before enabling this
    'EARTH-RESV',
    'EAS-RESV',
    'EDU-RESV',
    'ENG-RESV',
    'GREEN-RESV',
    'GSB-RESV',
    'HAS-NEWBK',
    'HOOV-RESV',
    'HOP-RESV',
    'IC-DISPLAY',
    'LANE-RESV',
    'LANG-RESV',
    'LAW-RESV',
    'LOAN-DESK',
    'MATH-RESV',
    'MEDIA-RESV',
    'MEYER-RESV',
    'MUSIC-RESV',
    'PHYS-RESV',
    'RESV-DESKS',
    'RESERVES',
    'TANN-RESV',
    'SSRC-NEWBK'
  ]

  RESERVE_DESKS = {
    'ART-RESV' => 'ART',
    'BIO-RESV' => 'BIOLOGY',
    'CHEM-RESV' => 'CHEMCHMENG',
    'E-RESV' => 'SW-E-RESV',
    'EARTH-RESV' => 'EARTH-SCI',
    'EAS-RESV' => 'EAST-ASIA',
    'EDU-RESV' => 'EDUCATION',
    'ENG-RESV' => 'ENG',
    'GREEN-RESV' => 'GREEN',
    'HOOV-RESV' => 'HOOVER',
    'HOP-RESV' => 'HOPKINS',
    'LAW-RESV' => 'LAW',
    'MATH-RESV' => 'MATH-CS',
    'MEDIA-RESV' => 'MEDIA-MTXT',
    'MUSIC-RESV' => 'MUSIC',
    'SCI-RESV' => 'SCIENCE'
  }

  STACKMAP_LIBS = %w(GREEN MEDIA-MTXT)

  HIDE_STACKMAP_LOCS = %w(BINDERY ENDPROCESS GRE-LOAN GREEN-RESV INPROCESS ON-ORDER REPAIR SL3-LOAN SLN-LOAN)

  INPROCESS_NONCIRC_LIBRARIES = ['RUMSEYMAP', 'SPEC-COLL'].freeze

  LIB_TRANSLATIONS = { # "APPLIEDPHY" => "Applied Physics Dept",
    'ARS' => 'Archive of Recorded Sound',
    'ART' => 'Art & Architecture Library (Bowes)',
    'BIOLOGY' => 'Biology Library (Falconer)',
    'CHEMCHMENG' => 'Chemistry & ChemEng Library (Swain)',
    'CLASSICS' => 'Classics Library',
    # "CPM" => "Obsolete",
    'EARTH-SCI' => 'Earth Sciences Library (Branner)',
    'EAST-ASIA' => 'East Asia Library',
    'EDUCATION' => 'Education Library (Cubberley)',
    'SW-E-RESV' => 'eReserve', # Library does not exist, this is an internal code used for reserves.
    'ENG' => 'Engineering Library (Terman)',
    'GOV-DOCS' => 'Green Library',
    'GREEN' => 'Green Library',
    'GRN-REF' => 'Green Library',
    'HOOVER' => 'Hoover Library',
    'HOPKINS' => 'Marine Biology Library (Miller)',
    'HV-ARCHIVE' => 'Hoover Archives',
    # "ILB" => "Ignore",
    'LANE-MED' => 'Medical Library (Lane)',
    'LATHROP' => 'Lathrop Library',
    'LAW' => 'Law Library (Crown)',
    'BUSINESS' => 'Business Library',
    'JACKSON' => 'Business Library',
    'MATH-CS' => 'Math & Statistics Library',
    'SW-MEDIA-RESV' => 'Media & Microtext Center', # Library does not exist, this is an internal code used for reserves.
    'MEDIA-MTXT' => 'Media & Microtext Center',
    'MEYER' => 'Meyer Library',
    'MUSIC' => 'Music Library',
    'RUMSEYMAP' => 'David Rumsey Map Center',
    # "PHYSICS" => "Stanford University Libraries",
    'SAL' => 'SAL1&2 (on-campus shelving)',
    'SAL3' => 'SAL3 (off-campus storage)',
    'SAL-NEWARK' => 'SAL Newark (off-campus storage)',
    'SCIENCE' => 'Science Library (Li and Ma)',
    'SPEC-COLL' => 'Special Collections',
    # "SPEC-DESK" => "(In-transit location for SAL paged items)",
    'TANNER' => 'Philosophy Library (Tanner)',
    'ZOMBIE' => 'Stanford University Libraries'
    # "SUL" => "Stanford University Libraries"
  }
  TRANSLATE_STATUS = {
    'available' => 'Available',
    'page' => 'Available',
    'unavailable' => 'Unavailable',
    'noncirc' => 'In-library use',
    'unknown' => 'Unknown',
    'noncirc_page' => 'In-library use'
  }
  HIDE_1ST_IND = %w(760 762 765 767 770 772 773 774 775 776 777 780 785 786 787)
  HIDE_1ST_IND0 = %w(541 542 561 583 590)
  CONTACT_INFO = {
    email: 'infocenter@stanford.edu',
    website: { label: 'SearchWorks', url: 'http://searchworks.stanford.edu' },
    libraries: [
      ['Green Library', '650 725 1064'],
      ['Meyer Library (Academic Computing)', '650 723 2434'],
      ['Green Library', '650 725 1064'],
      ['Art & Architecture Library', '650 723 3408'],
      ['Biology Library (Falconer)', '650 723 1528'],
      ['Business Library', '650 723 2162'],
      ['Chemistry and Chemical Engineering Library (Swain)', '650 723 9237'],
      ['Classics Library', '650 723 0479'],
      ['Earth Sciences Library (Branner)', '650 723 2746'],
      ['East Asia Library', '650 725 3435'],
      ['Education Library (Cubberley)', '650 723 2121'],
      ['Engineering Library (Terman)', '650 723 0001'],
      ['Hoover Institution Library', '650 723 2058'],
      ['Hoover Institution Archives', '650 723 3563'],
      ['Law Library (Crown)', '650 723 2477'],
      ['Map Collections (Branner Library)', '650 725 1103'],
      ['Marine Biology Library (Miller at Hopkins Marine Station)', '831 655 6229'],
      ['Math & Statistics Library', '650 723 4672'],
      ['Medical Library (Lane)', '650 723 6831'],
      ['Music Library', '650 723 1211'],
      ['Archive of Recorded Sound', '650 723 9312'],
      ['Philosophy Library (Tanner)', '650 723 1539'],
      ['Science Library (Li and Ma)', '650 723 1528'],
      ['Special Collections', '650 725 1022'],
      ['Stanford Auxiliary Library (SAL1&2)', '650 723 9201'],
      ['SLAC National Accelerator Laboratory Library', '650 926 2411']
    ]
    # No Physics or Meyer (ACOMP) in doc provided, the show up on web
  }

  HOURS_LOCATIONS = {
    'GREEN' => 'green/location/green_library',
    'SAL' => 'sal12/location/sal12_library',
    'MEYER' => 'meyer/location/meyer_24_hour',
    'ARS' => 'ars/location/ars_archive',
    'ART' => 'art/location/art_library',
    'BIOLOGY' => 'biology/location/biology_library',
    'CHEMCHMENG' => 'chemistry/location/chemistry_library',
    'EARTH-SCI' => 'earth_sciences/location/earth_sciences_library',
    'EAST-ASIA' => 'east_asia/location/east_asia_library',
    'EDUCATION' => 'education/location/education_library',
    'ENG' => 'engineering/location/engineering_library',
    'HOPKINS' => 'marine_biology/location/marine_biology_library',
    'MATH-CS' => 'math_stats/location/math_stats_library',
    'MEDIA-MTXT' => 'green/location/media_microtext',
    'MUSIC' => 'music/location/music_library',
    'RUMSEYMAP' => 'Rumsey/location/visitor-access',
    'SCIENCE' => 'science/location/library-circulation',
    'SPEC-COLL' => 'special_collections/location/spec_coll_reading',
    'BUSINESS' => 'business/location/business_library',
    'HV-ARCHIVE' => 'hoover_archives/location/hv_archives',
    'HOOVER' => 'hoover_library/location/hv_library',
    'LATHROP' => 'lathrop/location/tech-lounge',
    'LAW' => 'law/location/law_library',
    'LANE-MED' => 'medical/location/medical_library',
    'SLAC' => 'slac/location/slac'
  }

  LIBRARY_ABOUT = {
    'ARS' => 'http://library.stanford.edu/libraries/ars/about',
    'ART' => 'http://library.stanford.edu/libraries/art/about',
    'BIOLOGY' => 'http://library.stanford.edu/libraries/falconer/about',
    'BUSINESS' => 'http://library.stanford.edu/libraries/business/about',
    'CHEMCHMENG' => 'http://library.stanford.edu/libraries/swain/about',
    'EARTH-SCI' => 'http://library.stanford.edu/libraries/branner/about',
    'EAST-ASIA' => 'http://library.stanford.edu/libraries/eal/about',
    'EDUCATION' => 'http://library.stanford.edu/libraries/cubberley/about',
    'ENG' => 'http://library.stanford.edu/libraries/englib/about',
    'GREEN' => 'http://library.stanford.edu/libraries/green/about',
    'HOOVER' => 'http://library.stanford.edu/libraries/hoover/about',
    'HOPKINS' => 'http://library.stanford.edu/libraries/hopkins/about',
    'HV-ARCHIVE' => 'http://library.stanford.edu/libraries/hila/about',
    'LATHROP' => 'http://library.stanford.edu/libraries/lathrop/about',
    'LAW' => 'http://library.stanford.edu/libraries/law/about',
    'LANE-MED' => 'http://library.stanford.edu/libraries/lane/about',
    'MATH-CS' => 'http://library.stanford.edu/libraries/mathstat/about',
    'MUSIC' => 'http://library.stanford.edu/libraries/music/about',
    'MEDIA-MTXT' => 'http://library.stanford.edu/libraries/green/media-microtext-center',
    'MEYER' => 'http://library.stanford.edu/libraries/meyer/about',
    'RUMSEYMAP' => 'https://library.stanford.edu/libraries/rumsey/about',
    'TANNER' => 'http://library.stanford.edu/libraries/philosophy/about',
    'SPEC-COLL' => 'http://library.stanford.edu/libraries/spc/about',
    'SAL' => 'http://library.stanford.edu/libraries/sal/about',
    'SAL-NEWARK' => 'http://library.stanford.edu/libraries/newark/about',
    'SAL3' => 'http://library.stanford.edu/libraries/sal3/about',
    'SCIENCE' => 'http://library.stanford.edu/libraries/science/about',
    'SLAC' => 'http://library.stanford.edu/libraries/slac/about'
  }

  EXCLUDE_FIELDS = ['w', '0', '5', '6', '8', '?', '=']

  NIELSEN_TAGS = { '505' => '905', '520' => '920', '586' => '986' }
  SOURCES = { 'Nielsen' => '(source: Nielsen Book Data)' }
  SUL_ICONS = {
    'Object' => 'cube',
    'Archive/Manuscript' => 'document-box-1',
    'Archived website' => 'network-web',
    'Article' => 'text-wrapping-1',
    'Book' => 'book-1',
    'Dataset' => 'business-chart-1',
    'Database' => 'window-search',
    'Equipment' => 'plug-2',
    'Image' => 'photos-1',
    'Journal/Periodical' => 'book-2',
    'Map' => 'map-location',
    'Music recording' => 'gramophone',
    'Music score' => 'file-music',
    'Newspaper' => 'newspaper-2',
    'Software/Multimedia' => 'mouse-2',
    'Sound recording' => 'microphone-2',
    'Video' => 'film-2',
    'Credits' => 'contacts-1',
    'Subjects' => 'tags-1',
    'Contents' => 'list-4',
    'Browse' => 'books-3',
    'Chat' => 'bubble-2',
    'Feedback' => 'mail-1',
    'Cite' => 'quote',
    'Send To' => 'link',
    'Selections' => 'check-3'
  }
  BROWSABLE_CALLNUMBERS = %w(LC DEWEY ALPHANUM)

  LIBRARY_INSTRUCTIONS = {
    'RUMSEYMAP' => {
      heading: 'All items must be viewed on site',
      text: 'Request items by Noon (12p) the day before your visit to allow for retrieval by staff. You can request at most 5 items per day.'
    },
    'SPEC-COLL' => {
      heading: 'All items must be viewed on site',
      text: 'Request items at least 2 days before you visit to allow retrieval from off-site storage. You can request at most 5 items per day.'
    }
  }.freeze
end
