SEARCH_TIPS:
  - label: "For a known citation, type author name and title in the main search box."
    body: "<i>Example:</i> block bioenergetics of captive yellowfin tuna"
  - label: 'Start with keywords in the "All fields" search; add more keywords to refine.'
    body: "In articles+, adding more keywords to your search is often more effective than using facets."
  - label: "Enter your search in lower case or mixed case, never in ALL CAPS."
    body: "Some upper-case words in your search may be interpreted as boolean or field codes and will cause the search to fail."
  - label: "Search author names in last name, first name order to get more relevant results at the top."
    body: "<i>Example:</i>  cornell, eric  rather than   eric cornell"
  - label: "You can combine specific field searches using field codes: AU = Author; TI = Title; SU = Subject terms; SO = Journal/Source"
    body: "<i>Example:</i> AU block, barbara SO science"
  - label: "Stopwords are disregarded, even in quotes."
    body: "Searching for a title that contains only stopwords (\"to be or not to be\") is not possible. Try another approach: by author, subject, or by going directly to a <a href='/databases'>topic-specific database</a>."
  - label: "Not every source provides values for every facet; Geography in particular."
    body: "Caution: facets can exclude relevant items from your results simply because they are from a source that doesn't provide that metadata."
  - label: "Search results are de-duplicated on the fly, but facet counts are not."
    body: "A facet may indicate there are more articles on a topic than the final search result provides after de-duplication."
  - label: "AND, OR, and NOT (upper-case) are Boolean operators and can be combined with parentheses."
    body: "<i>Example:</i> tuna (yellowfin OR bluefin)"
  - label: "Search for non-English titles in quotation marks"
    body: "This helps ensure that non-English words like \"su\" and \"de\" are not interpreted as search codes."
  - label: "Use wildcards to search for spelling or word variations"
    body: "<ul><li># for 0 or 1 letter:  colo#r (finds color, colour)</li><li>? for 1 letter:  ne?t (finds next, nest, neat... but not net)</li><li>* for multiple letters:  comput* (finds computer, computing, computation)</li></ul>"
