# Can be removed once Aeon is re-enabled in main settings
aeon_locations:
  RUMSEYMAP: "*"
  SPEC-COLL: "*"
  HOOVER: "*"
  ARS:
    RECORDINGS: "*"
  EAST-ASIA:
    LOCKED-STK: "*"
    LOCK-STK-O: "*"
    LOCK-CHN: "*"
  SAL:
    L-PAGE-EA:
    - NH-INHOUSE
  SAL3:
    PAGE-AS: 
    - NH-INHOUSE
    PAGE-EA:
    - LCKSTK
